### ISSUE TITLE
导入您的demo

### ISSUE THREAD

**Issue by SmallBenClock** [eleme/Amigo#102]
Error:Could not find support-annotations.jar (com.android.support:support-annotations:24.1.0).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/support/support-annotations/24.1.0/support-annotations-24.1.0.jar

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

应该怎么解决?

**Comment by JackCho** [comment]
`support-annotations` library can not be found, you should use `Android SDK Manager` to download `Android Support Repository` first. This library cannot be found from jcenter, you may want to know this.
