### ISSUE TITLE
  Conflicts arise when access to a formal project

### ISSUE THREAD

**Issue by SmallBenClock** [eleme/Amigo#104]
What went wrong:
Execution failed for task ':app:processDevUniversalDebugManifest'.
> Cannot add task ':app:generateDevDebugApplicationInfo' as a task with that name already exists.

**Comment by FtheGFW** [comment]
Seems Amigo try to create two tasks with the same name during the build process, would you show us your own build.gradle file, please?

**Comment by JackCho** [comment]
no more further information here to use
