### ISSUE TITLE
新版本checkPatchPermission会出现异常

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#114]
今天发现Amigo更新到0.4.0版本，更新后测试，发现workLater出现异常，是在checkPatchPermission里面。
异常日志如下：
java.lang.UnsupportedOperationException
10-11 16:20:23.024 13874-17486/ W/System.err:     at java.util.AbstractList.remove(AbstractList.java:161)
10-11 16:20:23.025 13874-17486/ W/System.err:     at java.util.AbstractList$Itr.remove(AbstractList.java:374)
10-11 16:20:23.025 13874-17486/ W/System.err:     at java.util.AbstractCollection.removeAll(AbstractCollection.java:373)
10-11 16:20:23.025 13874-17486/ W/System.err:     at me.ele.amigo.utils.PermissionChecker.checkPatchPermission(PermissionChecker.java:31)
10-11 16:20:23.025 13874-17486/ W/System.err:     at me.ele.amigo.Amigo.checkPatchApk(Amigo.java:422)
10-11 16:20:23.025 13874-17486/com.mocoo.dfwc W/System.err:     at me.ele.amigo.Amigo.workLater(Amigo.java:384)
10-11 16:20:23.025 13874-17486/com.mocoo.dfwc W/System.err:     at com.mocoo.dfwc.Service.f.a(NotifyService.java:895)

**Comment by c1024** [comment]
网上查了一下，发现调用Arrays.asList()方法时把一个数组转化成List列表时，对得到的List列表进行add()和remove()操作时出现java.lang.UnsupportedOperationException异常

**Comment by peacepassion** [comment]
@c1024 好的，我看一下

**Comment by peacepassion** [comment]
@c1024  请升级到0.4.1。   

感谢反馈！
