### ISSUE TITLE
4.0.1版本 installHook会报异常

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#117]
更新到最新4.0.1版本，应用补丁重启后会看到如下异常：

HookFactory: installHook me.ele.amigo.hook.IActivityManagerHook@c58ef4a errorandroid.util.AndroidRuntimeException: Can not install IActivityManagerNative hook
                                                                 at me.ele.amigo.hook.IActivityManagerHook.onInstall(IActivityManagerHook.java:87)
                                                                 at me.ele.amigo.hook.HookFactory.installHook(HookFactory.java:23)
                                                                 at me.ele.amigo.hook.HookFactory.install(HookFactory.java:17)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at me.ele.amigo.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:33)
                                                                 at me.ele.amigo.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:40)
                                                                 at me.ele.amigo.Amigo.installHook(Amigo.java:188)
                                                                 at me.ele.amigo.Amigo.runPatchApk(Amigo.java:158)
                                                                 at me.ele.amigo.Amigo.onCreate(Amigo.java:112)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                 at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by peacepassion** [comment]
看到了。适配出了问题。 麻烦把设备、os信息发一下

**Comment by c1024** [comment]
Nexus 5 6.0系统 和 Nexus 6p 7.0系统都会

**Comment by peacepassion** [comment]
@c1024 我这边试了demo，nexus 6 7.0, nexus 5x 6.0.1, 都是OK的。  

你报问题的是demo，还是你接的项目？

**Comment by FtheGFW** [comment]
可以发个pr，修改一下IActivityManagerHook.onInstall里异常处理的逻辑，带上gDefault信息 @peacepassion

**Comment by c1024** [comment]
@peacepassion 我自己项目有问题

**Comment by peacepassion** [comment]
@c1024 那麻烦用同样的设备试下demo，看看demo的patch能否正常的work.  
thx.

**Comment by c1024** [comment]
@peacepassion 我测试了一下，同样设备demo没问题

**Comment by peacepassion** [comment]
@c1024 那这就有些麻烦了。那你们项目是不是用了DroidPlugin这类也会去hook ActivityManager的框架?

**Comment by c1024** [comment]
@peacepassion 我的项目应该是没用hook ActivityManager的框架

**Comment by peacepassion** [comment]
@c1024 是的。  那麻烦你帮忙断点跟一下吧，看看为什么落在了`else`中。  

调试文件：https://github.com/eleme/Amigo/blob/master/amigo-lib/src/main/java/me/ele/amigo/hook/IActivityManagerHook.java  

代码： 

![image](https://cloud.githubusercontent.com/assets/5254121/19336019/7e443e6e-913a-11e6-81fb-dea57673304e.png)

**Comment by c1024** [comment]
@peacepassion 你好，如果要调试，要把项目里面的amigo-lib ,buildsrc两个目录拷到项目里面是吧？还有怎么让gradle plugin 用自己，而不用网上的

**Comment by peacepassion** [comment]
@c1024 不需要拷贝这两个目录，直接通过Android Studio跳转到`IActivityManagerHook`这个类中，应该是一个`.class`文件，然后找到`onInstall`方法，在相应的代码处打上断点。

需要注意的是，`Attach debugger to Android Process`的时候一定要在dex loading结束之前搞定，否则，这段代码就过去了。

**Comment by c1024** [comment]
@peacepassion 这个加载一般差不多3秒，很多就过去，Attach debugger to Android Process估计来不及

**Comment by peacepassion** [comment]
可以提前把这个窗口准备好  
![image](https://cloud.githubusercontent.com/assets/5254121/19339823/4c7f01b6-9158-11e6-8b69-c35c393f28ac.png)

如果进程出现的话，就立即绑定   

若是不行的话，我们再想办法

**Comment by c1024** [comment]
@peacepassion 这样不行，来不及

**Comment by peacepassion** [comment]
@c1024 那就只能把`Amigo`项目拷贝一下了。    

1. 把这个项目下的`buildSrc` & `amigo-lib`两个目录拷贝到你的项目工程下，然后，把amigo plugin的依赖给删了，就是下面高亮的那行
![image](https://cloud.githubusercontent.com/assets/5254121/19340327/f11b453e-915a-11e6-99ee-425229c341a1.png)

2. 在`Amigo#onCreate`方法的最开始加一段Sleep代码。 

这样应该就可以了。

辛苦了，thx

**Comment by c1024** [comment]
@peacepassion 把Amigo demo使用混淆，发现异常，日志如下：

0-13 16:17:05.315 27890-27890/me.ele.app.amigo W/System.err: java.lang.ClassNotFoundException: Didn't find class "me.ele.app.amigo.receiver.DemoReceiver" on path: DexPathList[[zip file "/data/app/me.ele.app.amigo-1/base.apk"],nativeLibraryDirectories=[/data/app/me.ele.app.amigo-1/lib/arm64, /system/lib64, /vendor/lib64]]
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.utils.component.ReceiverFinder.registerNewReceivers(Unknown Source)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.Amigo.dynamicRegisterReceivers(Unknown Source)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Unknown Source)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.Amigo.onCreate(Unknown Source)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at android.os.Looper.loop(Looper.java:154)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
10-13 16:17:05.316 27890-27890/me.ele.app.amigo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-13 16:17:05.317 27890-27890/me.ele.app.amigo W/System.err: me.ele.amigo.Amigo$LoadPatchApkException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "me.ele.app.amigo.receiver.DemoReceiver" on path: DexPathList[[zip file "/data/app/me.ele.app.amigo-1/base.apk"],nativeLibraryDirectories=[/data/app/me.ele.app.amigo-1/lib/arm64, /system/lib64, /vendor/lib64]]
10-13 16:17:05.317 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Unknown Source)
10-13 16:17:05.317 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.Amigo.onCreate(Unknown Source)
10-13 16:17:05.317 27890-27890/me.ele.app.amigo W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at android.os.Looper.loop(Looper.java:154)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err: Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "me.ele.app.amigo.receiver.DemoReceiver" on path: DexPathList[[zip file "/data/app/me.ele.app.amigo-1/base.apk"],nativeLibraryDirectories=[/data/app/me.ele.app.amigo-1/lib/arm64, /system/lib64, /vendor/lib64]]
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.utils.component.ReceiverFinder.registerNewReceivers(Unknown Source)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at me.ele.amigo.Amigo.dynamicRegisterReceivers(Unknown Source)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err: 	... 12 more
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "me.ele.app.amigo.receiver.DemoReceiver" on path: DexPathList[[zip file "/data/app/me.ele.app.amigo-1/base.apk"],nativeLibraryDirectories=[/data/app/me.ele.app.amigo-1/lib/arm64, /system/lib64, /vendor/lib64]]
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-13 16:17:05.318 27890-27890/me.ele.app.amigo W/System.err: 	... 14 more

我发现用debug版不会发现异常，如果用混淆，demo和我自己的项目就会有问题

**Comment by c1024** [comment]
@peacepassion 前面异常跟proguard配置有问题，把prouard-rules设置好后，异常就跟我类似。问题应该出在混淆上

**Comment by c1024** [comment]
@peacepassion 应该是在SingletonCompat里面失败。isInstance方法返回false

**Comment by peacepassion** [comment]
@c1024 是的。这边正在修复。
