### ISSUE TITLE
gradle plugin能不能提供选项设置是否启用Amigo？

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#121]
因为Google play的限制，使用Amigo每次发布要发布两个版本，一个用Amigo，一个不用。每次都要注释，取消注释，这样很麻烦。gradle plugin能不能提供选项设置是否启用Amigo？

**Comment by peacepassion** [comment]
这个应该可以做到。  我们这边尽快实现

**Comment by JackCho** [comment]
There is no need to do this, so we decide not to support this feature
