### ISSUE TITLE
应用补丁后启动时间能否再优化？

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#122]
多次测试后，发现应用补丁后启动时间比没用补丁多3秒左右。感觉太长，对用户来说体验还是不太友好，能否再优化？

**Comment by peacepassion** [comment]
@c1024 怎么确认启动时间多了3s?  帮忙贴一下启动时amigo打出的log.

**Comment by c1024** [comment]
我自己项目会这样，可能apk比较大缘故，有10MB以上。

**Comment by c1024** [comment]
10-16 16:28:52.191 782-1649/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.mocoo.dfwc/.GuideActivity bnds=[327,324][507,504] (has extras)} from uid 11447 on display 0
10-16 16:28:52.226 782-1877/? I/ActivityManager: Start proc 26436:com.mocoo.dfwc/u0a1447 for activity com.mocoo.dfwc/.GuideActivity
10-16 16:28:52.353 26436-26436/com.mocoo.dfwc W/art: No such thread id for suspend: 10
10-16 16:28:52.354 26436-26436/com.mocoo.dfwc E/Amigo: working checksum: 4197493118
10-16 16:28:55.410 26436-26436/com.mocoo.dfwc E/Amigo: patchApkChecksum-->4197493118, sp record checksum--->4197493118
10-16 16:28:55.415 26436-26436/com.mocoo.dfwc E/Amigo: opt dexFile-->/data/user/0/com.mocoo.dfwc/code_cache/4197493118/amigo-dexes/classes.dex
10-16 16:28:55.415 26436-26436/com.mocoo.dfwc E/Amigo: savedChecksum-->1733791403, checksum--->1733791403
10-16 16:28:55.424 26436-26436/com.mocoo.dfwc W/System: ClassLoader referenced unknown path: 
10-16 16:28:55.442 26436-26436/com.mocoo.dfwc E/Amigo: oldInstrumentation--->android.app.Instrumentation@6c910de
10-16 16:28:55.443 26436-26436/com.mocoo.dfwc E/Amigo: setApkInstrumentation success classloader-->dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mocoo.dfwc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mocoo.dfwc-1/lib/arm, /data/app/com.mocoo.dfwc-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
10-16 16:28:55.444 26436-26436/com.mocoo.dfwc E/Amigo: hook handler success
10-16 16:28:55.474 26436-26436/com.mocoo.dfwc E/Amigo: clear old patches
10-16 16:28:55.582 26436-26436/com.mocoo.dfwc I/IActivityManagerHook: Install ActivityManager Hook 2 old=android.app.ActivityManagerProxy@908b151,new=android.app.ActivityManagerProxy@908b151
10-16 16:28:55.583 26436-26436/com.mocoo.dfwc E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@908b151,new=android.app.ActivityManagerProxy@908b151
10-16 16:28:55.588 26436-26436/com.mocoo.dfwc I/MultiDex: VM with version 2.1.0 has multidex support
10-16 16:28:55.588 26436-26436/com.mocoo.dfwc I/MultiDex: install
10-16 16:28:55.588 26436-26436/com.mocoo.dfwc I/MultiDex: VM has multidex support, MultiDex support library is disabled.
10-16 16:28:55.621 26436-26436/com.mocoo.dfwc D/PRETTYLOGGER: ╔════════════════════════════════════════════════════════════════════════════════════════
10-16 16:28:55.622 26436-26436/com.mocoo.dfwc D/PRETTYLOGGER: ║ Amigo.onCreate  (Amigo.java:112)
10-16 16:28:55.622 26436-26436/com.mocoo.dfwc D/PRETTYLOGGER: ║    Amigo.runPatchApk  (Amigo.java:159)
10-16 16:28:55.622 26436-26436/com.mocoo.dfwc D/PRETTYLOGGER: ╟────────────────────────────────────────────────────────────────────────────────────────
10-16 16:28:55.622 26436-26436/com.mocoo.dfwc D/PRETTYLOGGER: ║ application onCreate
10-16 16:28:55.622 26436-26436/com.mocoo.dfwc D/PRETTYLOGGER: ╚════════════════════════════════════════════════════════════════════════════════════════

**Comment by peacepassion** [comment]
```
10-16 16:28:52.354 26436-26436/com.mocoo.dfwc E/Amigo: working checksum: 4197493118
10-16 16:28:55.410 26436-26436/com.mocoo.dfwc E/Amigo: patchApkChecksum-->4197493118, sp record checksum--->4197493118
```
这两个log之间话费了3s，检查了一下代码，最有可能耗在了验证签名上 `Amigo#checkSinature()`上了。  

@c1024 @JackCho

**Comment by JackCho** [comment]
Fixed in https://github.com/eleme/Amigo/pull/125
