### ISSUE TITLE
看到日志：HookedMethodHandler: doHookInner method(android.app.IActivityManager.bindService) cost 1610 ms 。这个会影响性能吗？

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#126]
更新了最新0.4.3版本，测试中看到日志HookedMethodHandler: doHookInner method(android.app.IActivityManager.bindService) cost 1610 ms 。
这个会影响运行性能吗？

**Comment by JackCho** [comment]
@c1024 please upgrade to [0.5.0](https://github.com/eleme/Amigo/blob/master/CHANGELOG.md#version-050)

**Comment by c1024** [comment]
@JackCho 更新测试一下，有如下日志，是正常吗？
11-03 22:59:08.242 6212-6261/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.content.pm.IPackageManager.getApplicationInfo) cost 33 ms
11-03 22:59:08.257 6212-6268/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.bindService) cost 30 ms
11-03 22:59:08.611 6212-6212/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.startService) cost 12 ms
11-03 22:59:08.637 6212-6212/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.startService) cost 23 ms
11-03 22:59:08.651 6212-6212/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.startService) cost 13 ms
11-03 22:59:08.788 6212-6212/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.startService) cost 26 ms
11-03 22:59:08.908 6286-6286/? I/HookedMethodHandler: doHookInner method(android.content.pm.IPackageManager.getApplicationInfo) cost 24 ms
11-03 22:59:08.913 6212-6212/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.stopServiceToken) cost 23 ms
11-03 22:59:08.926 6286-6323/? I/HookedMethodHandler: doHookInner method(android.content.pm.IPackageManager.getApplicationInfo) cost 9 ms
11-03 22:59:08.958 6286-6337/? I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.bindService) cost 30 ms
11-03 22:59:09.009 6286-6286/? I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.bindService) cost 15 ms
11-03 22:59:09.070 6286-6337/? I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.unbindService) cost 14 ms
11-03 22:59:09.321 6212-6405/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.bindService) cost 25 ms
11-03 22:59:10.609 6212-6212/com.mocoo.dfwc I/HookedMethodHandler: doHookInner method(android.app.IActivityManager.startService) cost 24 ms

**Comment by JackCho** [comment]
嗯，优化的力度还不够强烈。我们后期会继续在这方面努力，感谢反馈，我把这个issue再reopen起来。

@FtheGFW 你抽空看看
