### ISSUE TITLE
multi-process workflow

### ISSUE THREAD

**Issue by peacepassion** [eleme/Amigo#13]
Now, in the `Amigo` application, if not run by main process, just `runOriginalApplication` and return.   

However, this workflow has an deficiency that we fail to fix those bugs from the code used only in none-main process.

**Comment by peacepassion** [comment]
@JackCho There would be following conditions when entering `Amigo#onCreate`.  
1. Main process. Just run current code.  
2. None main process without UI, like service in the background. The best procedure is checking if it need to fix at first, if YES, try to load patch apk in the background, if NO, just run original code.  
3. None main process with UI, like an activity declared in other process. The best procedure is similar as the above situation, and the difference is load patch apk in the foreground with a loading UI.  

This kind of ideal processing looks quite complicated, and the degree of necessity is not high.  

So I recommend just check if there are loaded hot patch there and if YES, use Amigo classloader, with patch apk, it not, use orignal classloder.

**Comment by FtheGFW** [comment]
amigo加载patch apk的进程肯定是在别的进程之前运行的吧，那是不是运行在新进程里的service等的bug(若存在)就已经被修复了？ @JackCho

**Comment by JackCho** [comment]
@FtheGFW yes, if any class is changed, it will work. 
do not support new added components for now, just support activity & receiver in beta version

**Comment by JackCho** [comment]
see in https://github.com/eleme/Amigo/pull/18
