### ISSUE TITLE
多渠道，怎么打出增量包！！！

### ISSUE THREAD

**Issue by yang747046912** [eleme/Amigo#133]
app 有多个渠道包，我需要根据不同渠道打出不同的增量包吗？

**Comment by FtheGFW** [comment]
Hi，Amigo项目本身只负责把输入给他的完整apk运行起来，暂时还没有集成打/合成增量包的功能，所以得你自己做这些相关的处理代码了 （  :dog:

**Comment by JackCho** [comment]
渠道包该怎么打还怎么打。如果出现bug，打包一个修复问题的`patch.apk`；然后分别与各个渠道包进行差分；客户端请求hotfix接口的时候，基于不同的渠道包下发不同的差分包。这一系列的操作都需要后端同学的支持，希望可以帮助到你
