### ISSUE TITLE
Infinity loop issue

### ISSUE THREAD

**Issue by macczakdeveloper** [eleme/Amigo#142]
> W/System: ClassLoader referenced unknown path: /data/app/hello.amigo.checker-1/lib/arm
> 11-03 07:10:43.623 1156-1156/? E/Amigo: working checksum: 2141471880
> 11-03 07:10:43.627 1156-1156/? E/amigo_patch_cleaner: clear without patch
> 11-03 07:10:43.627 1156-1156/? E/amigo_patch_cleaner: remove file: /data/data/hello.amigo.checker/files/amigo/2141471880/dexes
> 11-03 07:10:43.628 1156-1156/? E/amigo_patch_cleaner: remove file: /data/data/hello.amigo.checker/files/amigo/2141471880/libs
> 11-03 07:10:43.629 1156-1156/? W/System.err: me.ele.amigo.exceptions.LoadPatchApkException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
> 11-03 07:10:43.630 1156-1156/? W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Amigo.java:145)
> 11-03 07:10:43.630 1156-1156/? W/System.err:     at me.ele.amigo.Amigo.onCreate(Amigo.java:87)
> 11-03 07:10:43.630 1156-1156/? W/System.err:     at me.ele.amigo.Amigo.releasePatchApk(Amigo.java:235)
> 11-03 07:10:43.630 1156-1156/? W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Amigo.java:115)
> 11-03 07:10:43.658 1829-3107/? I/ActivityManager: Process hello.amigo.checker:amigo (pid 1106) has died
> 11-03 07:10:43.893 1829-4239/? I/ActivityManager: Start proc 1170:hello.amigo.checker:amigo/u0a436 for service hello.amigo.checker/me.ele.amigo.AmigoService
> 11-03 07:10:43.919 263-263/? D/SFPerfTracer:        layers: (5:17) (FocusedStackFrame (0xb8d02548): 1:1010)* (DimLayer (0xb8d67250): 0:236)* (StatusBar (0xb8d6f3c8): 0:7710) (com.android.systemui.ImageWallpaper (0xb8cddc70): 0:518) (NavigationBar (0xb8cdc9a8): 9:1481) (DimLayer (0xb8d78500): 0:3)- (Starting hello.amigo.checker (0xb8d5b330): 0:27)- (com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (0xb8d3a718): 0:4)- (DimLayer (0xb8d5ef90): 0:2)- (Starting hello.amigo.checker (0xb8d7a458): 0:28)- (com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (0xb8d3a718): 0:3) (DimLayer (0xb8d5ef90): 1:1)* (Starting hello.amigo.checker (0xb8d7a458): 19:21) 
> 11-03 07:10:43.931 1170-1170/? W/System: ClassLoader referenced unknown path: /data/app/hello.amigo.checker-1/lib/arm
> 11-03 07:10:43.942 1170-1170/? E/Amigo: working checksum: 2141471880
> 11-03 07:10:43.945 1170-1170/? E/Amigo: load dex process
> 11-03 07:10:43.959 1829-4533/? I/ActivityManager: Process hello.amigo.checker (pid 1156) has died
> 11-03 07:10:43.973 1829-4533/? I/ActivityManager: Start proc 1185:hello.amigo.checker/u0a436 for activity hello.amigo.checker/.MainActivity
> 11-03 07:10:44.018 1185-1185/? W/System: ClassLoader referenced unknown path: /data/app/hello.amigo.checker-1/lib/arm
> 11-03 07:10:44.028 1185-1185/? E/Amigo: working checksum: 2141471880
> 11-03 07:10:44.031 1185-1185/? E/amigo_patch_cleaner: clear without patch
> 11-03 07:10:44.032 1185-1185/? E/amigo_patch_cleaner: remove file: /data/data/hello.amigo.checker/files/amigo/2141471880/dexes
> 11-03 07:10:44.032 1185-1185/? E/amigo_patch_cleaner: remove file: /data/data/hello.amigo.checker/files/amigo/2141471880/libs
> 11-03 07:10:44.033 1185-1185/? W/System.err: me.ele.amigo.exceptions.LoadPatchApkException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
> 11-03 07:10:44.033 1185-1185/? W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Amigo.java:145)
> 11-03 07:10:44.033 1185-1185/? W/System.err:     at me.ele.amigo.Amigo.onCreate(Amigo.java:87)
> 11-03 07:10:44.034 1185-1185/? W/System.err:     at me.ele.amigo.Amigo.releasePatchApk(Amigo.java:235)
> 11-03 07:10:44.034 1185-1185/? W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Amigo.java:115)
> 11-03 07:10:44.466 1829-4396/? I/ActivityManager: Process hello.amigo.checker (pid 1185) has died
> 11-03 07:10:44.589 1829-4395/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x34000000 pkg=hello.amigo.checker cmp=hello.amigo.checker/.MainActivity} from uid 10436 on display 0
> 11-03 07:10:44.590 1170-1170/? E/AmigoService: start launchIntent

It's repeating closing, opening, closing, opening... infinity loop.

Here is how I am triggering amigo on my activity:

```
` public void applyPatchApkImmediately() {
        File dir = Environment.getExternalStorageDirectory();
        File patchApkFile = new File(dir, "demo.apk");
        if (!patchApkFile.exists()) {


            Toast.makeText(this,
                    "No amigo_patch.apk found in the directory: " + dir.getAbsolutePath(),
                    Toast.LENGTH_LONG).show();
            return;
        }
        boolean patchWorked = Amigo.hasWorked();
        if (!patchWorked) {
            Amigo.work(this, patchApkFile);
            return;
        }
        int workingPatchVersion = Amigo.workingPatchVersion(getApplication());
        if (workingPatchVersion >= CommonUtils.getVersionCode(getApplication(), patchApkFile)) {
            Toast.makeText(this, patchApkFile.getAbsolutePath()
                    + " version must be newer than current working patch", Toast.LENGTH_LONG)
                    .show();
            return;
        }
        Amigo.work(this, patchApkFile);
    }`

```

Android version 6.0
API used 22
Build tools used 22.0.1
Phone: Motorola G3

**Comment by FtheGFW** [comment]
估计是metadata为空，我们这边重现不了，你可以帮忙打开Amigo.class打个断点试试

**Comment by JackCho** [comment]
no further info to provide here, close this issue temporarily.
if any info is provided, then I will reopen this.
