### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by macczakdeveloper** [eleme/Amigo#156]
Operation takes usualy 20 seconds, how to put my custom layout for operation?

<meta-data
    android:name="amigo_layout"
    android:value="{your-layout-name}" />

<meta-data
    android:name="amigo_theme"
    android:value="{your-theme-name}" />

i know layout - some xml with layout but theme? Should I put style or what inside?

**Comment by FtheGFW** [comment]
Just put your custom theme declaration inside main/res/theme.xml or main/res/styles.xml
