### ISSUE TITLE
Skipping compilation of void 

### ISSUE THREAD

**Issue by macczakdeveloper** [eleme/Amigo#158]
Skipping compilation of void  com.faspnqvq.hdammrlw147536.o$4.a(): it contains a non natural loop

Same jackson library. Can we somehow bypass it? I'm loosing the possibility to use these libraries. Before amigo work, libraries are working fine.

**Comment by JackCho** [comment]
I didn't follow you,  please provider more info.

but first I suggest you should try `0.6.0-beta` instead with current version

**Comment by JackCho** [comment]
no more info here, so close this issue
