### ISSUE TITLE
patch版本号升级

### ISSUE THREAD

**Issue by wznshuai** [eleme/Amigo#161]
在打patch包的时候在gradle里面其实已经升级了versionName 和 versionCode , 但是修复成功后取到的versionName还是Host的老版本号。版本号这个有什么好的方案？

**Comment by wznshuai** [comment]
boolean patchWorked = Amigo.hasWorked();
                if (!patchWorked) {
                  
                    return  DeviceInfo.getVersionCode(context);
                }
                return Amigo.workingPatchVersion(context);

是不是要写这样类似的兼容？

**Comment by JackCho** [comment]
@wznshuai version_name和version_code的问题已在0.6.0-beta里面修复。
现在如果patch生效的话，获取到的版本信息都是patch apk的，如果你仍想获得原本host的版本信息，可以通过这段代码：
```java
Amigo.getHostPackageInfo(Context context, int flags)
```

**注意:** 在请求是否patch的接口里面，一定要传递host的版本信息
