### ISSUE TITLE
资源支持

### ISSUE THREAD

**Issue by zhousuqiang** [eleme/Amigo#167]
请问支持raw目录下的资源吗？

**Comment by JackCho** [comment]
yes

**Comment by zhousuqiang** [comment]
@JackCho 你好，再咨询下版本之间的差异包的问题，比如：
版本1.0.0通过amigo更新到了1.0.1,那么1.0.2版本发布了，请问之前升级到1.0.1版本的用户直接更新1.0.1到1.0.2的差异包吗，还是总要从1.0.0到最新版本出差异包？
