### ISSUE TITLE
Amigo平台找不到问题

### ISSUE THREAD

**Issue by GongZiZhang** [eleme/Amigo#170]
问题log：
Error:Could not find me.ele:amigo_sdk:1.0.0.
Required by:
    diaoyur_android:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

已经把jcenter加入到repositories

repositories {
    jcenter()
    ...
}

**Comment by JackCho** [comment]
sorry， jcenter审核抽疯了，要等会，可以先用这个workaround

```groovy
maven {
      url "https://dl.bintray.com/jackcho/maven"
 }
```

**Comment by JackCho** [comment]
amigo站点文档已更新，抱歉
