### ISSUE TITLE
Wrong meta-data name in document

### ISSUE THREAD

**Issue by John-Constantine** [eleme/Amigo#172]
https://amigo.ele.me/#/wiki/add-sdk
![image](https://cloud.githubusercontent.com/assets/10413226/21059688/b2897056-be7e-11e6-85ef-ba6fd0dbadc1.png)

I follow this document to add <meta-data> with name="Amigo" in AndroidManifest.xml.like this
![image](https://cloud.githubusercontent.com/assets/10413226/21059862/79e1e886-be7f-11e6-8944-5509a867176c.png)

After I install app and launch it.It occur NullPointerException.like this
![image](https://cloud.githubusercontent.com/assets/10413226/21060100/a8e6c894-be80-11e6-888e-52c12b407c9b.png)

I check the code and find the code get "amigo_app_id" value from AndroidManifest.xml
![image](https://cloud.githubusercontent.com/assets/10413226/21060231/3c22c068-be81-11e6-8092-7c532115d5c9.png)
So I think the document is wrong.You should change meta name "Amigo"  into "amigo_app_id"

**Comment by FtheGFW** [comment]
@peacepassion

**Comment by peacepassion** [comment]
@John-Constantine You are right.  Sorry for your inconvenience.   We'll fix it asap.
