### ISSUE TITLE
Unable to read AndroidManifest.xml

### ISSUE THREAD

**Issue by John-Constantine** [eleme/Amigo#173]
![image](https://cloud.githubusercontent.com/assets/10413226/21060542/e4c62e5c-be82-11e6-8865-b713e9397f7a.png)

**Comment by FtheGFW** [comment]
@peacepassion

**Comment by peacepassion** [comment]
@John-Constantine 看上去是patch没对上，导致合成出来的文件不是一个合法的apk。  

麻烦确认一下上传的patch是不是正确的patch.apk与host.apk求解出的。

**Comment by John-Constantine** [comment]
![image](https://cloud.githubusercontent.com/assets/10413226/21087266/3d7844bc-c05f-11e6-8b11-11a4c96af85c.png)

发布补丁的时候上传补丁我选择的是解决掉bug的apk，然后选择了差分，应用上传原始apk选择的是我安装到手机上的有bug的apk。我的理解是Amigo的后端会根据这两个apk生成一个patch，然后再下发这个生成的patch。不知道我理解的是否正确？

**Comment by peacepassion** [comment]
你的理解是正确的。 

你们发了几个patch？

**Comment by John-Constantine** [comment]
发了3个patch，想删除前面两个patch点清空页面也没有什么反应

**Comment by JackCho** [comment]
@John-Constantine 你没有必要去删除前面的patch版本，只需叠加发布就可以。这个问题的原因看日志是本地patch好的APK不是一个合法的APK，你检查一下你上传的APK是否是你安装到自己机器上的，如有不确定，可以把机器里面的APP 通过 adb pull出来

**Comment by wm1993** [comment]
@John-Constantine   我现在也碰到这样的情况

**Comment by wm1993** [comment]
@John-Constantine   你的问题搞定了没有？

**Comment by John-Constantine** [comment]
没有搞定，最近忙新项目，没有时间研究

**Comment by wm1993** [comment]
@John-Constantine   问题出在打包上面，我的解决了。具体是这样的：1上传Amigo平台的两个apk（一个补丁apk（用A  apk表示），一个用户使用出现的问题apk（用B apk表示）），这两个apk一定是同一种方式打包出来的（debug,release）,我这边用的是Debug打的包，让后上传，2，卸载手机上安装的app，3 安装B apk   运行一下就好了，切记不要直接用AS直接运行，找了半天的原因就是：直接运行导致的，虽然都是Debug。  可以试试   我说的步骤 。

**Comment by John-Constantine** [comment]
@wm1993 的确是这样，我应该也是用AS直接运行的才出现了这个问题，多谢

**Comment by JackCho** [comment]
@wm1993 thx for solving this issue
