### ISSUE TITLE
根据文档没办法跑起来，麻烦前辈帮忙看看

### ISSUE THREAD

**Issue by AlphaHans** [eleme/Amigo#174]
根据最新的官网配置的：
```
classpath 'me.ele:amigo:0.6.1'

compile 'me.ele:amigo_sdk:1.0.1'
```
官网文档的错误已经自己DEBUG发现并修改为：
```
<meta-data
            android:name="amigo_app_id"
            android:value="我的key"/>
```
我的步骤是
* 1.生成版本名为2.0 版本号为2的 第一个APK。 里面只有一个TEXTVIEW写着修复前
* 2.生成版本名位2.1 版本号为3的 第二个APK。 里面也是只有一个TEXTVIEW写着修复后
* 3.到Amigo平台配置
![1](http://p1.bqimg.com/567571/34300a328505d2ce.png)
![2](http://p1.bqimg.com/567571/8622ae1fecd2f95b.png)
* 4.重新打开APP 过一会之后APP重启，然后就闪退。 LOG消息如下
![3](http://p1.bqimg.com/567571/bf03159322e959aa.png)

**Comment by AlphaHans** [comment]
```
12-12 01:12:15.584 7855-7855/? I/Process: Sending signal. PID: 7855 SIG: 9
```
应该是这里直接结束了进程，由于能力有限，还没开始看源代码，接触热修复不久，麻烦前辈可以指导一下

**Comment by AlphaHans** [comment]
尝试跟踪了一下源代码，发现到了最后一句这个.
![](http://p1.bpimg.com/567571/9d8f1ee366c237ce.png)
这里的逻辑是，启动`AmigoService`并且反射结束掉所有的`Activity`

然后我切换到`AmigoService`所在进程发现Service确实启动了
![](http://p1.bpimg.com/567571/a78342e70950fe0e.png)
重试新尝试拉起：
![](http://p1.bpimg.com/567571/29bc88e2852a99f1.png)
发现最终执行到：
```
    private void pullUpMainProcess(Context context) {
        if (ProcessUtils.isMainProcessRunning(context)) {
            return;
        }
        ProcessUtils.startLauncherIntent(context);
    }
```
这里过程是什么情况呢...为何这么奇怪呢。  T^T

**Comment by AlphaHans** [comment]
```
 private static void work(Context context, File patchFile, boolean checkSignature) {
        String patchChecksum = PatchChecker.checkPatchAndCopy(context, patchFile, checkSignature);
        if (checkWithWorkingPatch(context, patchChecksum)) return;
        if (!PatchInfoUtil.setWorkingChecksum(context, patchChecksum)) return;
        KillSelfActivity.start(context);
    }
```
又掉头回去看了一下，也就是说
```
if (checkWithWorkingPatch(context, patchChecksum)) return;
if (!PatchInfoUtil.setWorkingChecksum(context, patchChecksum)) return;
```
都没有起作用。
第一个应该是检查当前这个Patch包是否已经生效了（简单看了一下使用CRC32判断），如果生效则返回。（ 即不理会这次patch包）
第二个应该是将这次的的Patch更新不成功，则会返回。

那么梳理之后的逻辑就是：
1.拷贝patch包和应用patch包
2.如果该patch包已经存在，则不做任何事情，并返回
3.如果更新patch包信息失败，也返回
4.如果更新成功，那么重启应用（表明APK修复成功？）

不知道上面的逻辑理解是否有错误呢....

好像问的比较多了，麻烦前辈有空的时候回答一下，谢谢。

**Comment by AlphaHans** [comment]
由于配置出错的问题- - 
```
//开发阶段可选不启用
amigo {
    disable true //默认 false
}

```
这里我不应该设置为true....

**Comment by JackCho** [comment]
@AlphaHans 不好意思，这两天在外面。嗯，看到你一个人就把问题解决了👍 你把Amigo主要的东西都理清了，基本就是这个意思，感谢你的反馈

**Comment by AlphaHans** [comment]
@JackCho 非常感谢前辈将如此棒的项目开源出来，代码写的很exciting呢！
目前在尝试看Amigo的lib中的逻辑了，希望离开学校之前给团队引入一个热修复框架，所以希望自己爬坑完，给师弟们留下一些知识。
如果有问题会继续前来指教。明年校招投一下饿了么的简历，看看到时候有机会和前辈一起学习。哈哈。

**Comment by LeonXtp** [comment]
@AlphaHans 现在在饿了么了吗？
