### ISSUE TITLE
Cannot add task as a task with that name already exists.

### ISSUE THREAD

**Issue by wznshuai** [eleme/Amigo#175]
:myproject:mergeSjzs360DebugResources
:myproject:dataBindingProcessLayoutsSjzs360Debug
:myproject:processSjzs360ArmeabiDebugManifest
generateCodeTask execute
:myproject:processSjzs360ArmeabiDebugResources
:myproject:processSjzs360X86DebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myproject:processSjzs360X86DebugManifest'.
> Cannot add task ':myproject:generateSjzs360DebugApplicationInfo' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

当amigo {
    disable false //default false
}为false的时候 就会报这个
@JackCho @FtheGFW

**Comment by wznshuai** [comment]
amigo plugin version: 0.6.1
taskName -- :myprojectlibrary:generateDebugSources
debug copy
taskName -- :myprojectlibrary:mockableAndroidJar
taskName -- :myprojectlibrary:prepareDebugUnitTestDependencies
debug copy
taskName -- :myprojectlibrary:generateDebugAndroidTestSources
debug copy
taskName -- :myproject:generateSjzs360DebugSources
debug copy
taskName -- :myproject:mockableAndroidJar
taskName -- :myproject:prepareSjzs360DebugUnitTestDependencies
debug copy
taskName -- :myprojectp2p:generateSjzs360DebugAndroidTestSources
debug copy
check instant run
check instant run

好像被执行了两次  什么情况造成的呢

**Comment by wznshuai** [comment]
![image](https://cloud.githubusercontent.com/assets/1897647/21169925/a1a9d778-c1fb-11e6-8e70-0cc1995c4a7a.png)
红线部分会在我lib工程和业务工程创建完成都触发一次？

**Comment by wznshuai** [comment]
splits {

        // Configures screen ABI split settings
        abi {

            // Enable ABI APK splits
            enable true

            // By default all ABIs are included, so use reset() and include to specify that we only
            // want APKs for x86, armeabi-v7a, and mips

            // Resets the list of ABIs that Gradle should create APKs for to none
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for
            include "armeabi", "x86"
        }
    }
我 gradle里面有这个配置，去掉了 就不报那个错误了  什么情况 请指导一哈

**Comment by JackCho** [comment]
```grovvy
project.tasks.create(name: "generate${variant.name.capitalize()}ApplicationInfo", type: GenerateCodeTask)
```

创建Task的时候是基于variant.name创建的，每一个variant都是独特的。你尝试什么度不做修改的情况下，在 `./gradlew assemble` 改为 `./gradlew clean assemble`

**Comment by FtheGFW** [comment]
fixed @wznshuai
