### ISSUE TITLE
自定义加载界面横屏可以设置么

### ISSUE THREAD

**Issue by qinqinany** [eleme/Amigo#177]
App以横屏方式开发的，插件处理时切换为竖屏了

**Comment by JackCho** [comment]
这个需求前期没有考虑到，我们会尽快帮忙解决，届时会在这个issue里面进行告知

**Comment by JackCho** [comment]
Amigo has supported this feaure, please try with [amigo_orientation](https://github.com/eleme/Amigo#customize-loading-pageoptional)

and upgrade amigo plugin to `0.6.2`
```groovy
classpath 'me.ele:amigo:0.6.2'
```

**Comment by qinqinany** [comment]
好的，收到
