### ISSUE TITLE
在三星GT-P7510 4.0.4版本中，无法正常运行

### ISSUE THREAD

**Issue by qinqinany** [eleme/Amigo#179]
1.App在模拟器中，可以正常运行，
2.在三星的平板中，调用Amigo.work之后，应用关闭，无法重新启动，且重新打开之后，还是之前的版本，没有修复过的
3.后台没有异常

**Comment by FtheGFW** [comment]
能把adb logcat输出的日志上传一下吗

**Comment by qinqinany** [comment]
额，是我配置的问题，amigo { disable true} 发布的时候，忘记改为false了
