### ISSUE TITLE
Gives Google play service update alert whenever i apply patch

### ISSUE THREAD

**Issue by atulgoswami21** [eleme/Amigo#182]
Gives Google play service update alert whenever i apply patch and full description is "me.ele.amigo.Amigo won't run unless you update Google Play Services.
And in logcat it shows "W/GooglePlayServicesUtil: Google Play services out of date.  Requires 8487000 but found 34" and here 34 is my version code of application and 8487000 is defined in manifest metadata.

Please help me as i have no clue what is going on. Even i have used same apk for patch and host.

**Comment by FtheGFW** [comment]
Is your own demo app's package name "me.ele.amigo.Amigo" ? 
What is number 8487000 defined you manifest used for ?
Can you give us some hint on what features are you using of google play service? so we can re-produce you problem @atulgoswami21

**Comment by atulgoswami21** [comment]
I am using google play service for user activity recognition and tracking their location. for this to work properly i am checking google play service availability i am using 

 public static boolean checkPlayServicesNew(Context ctx) {
        GoogleApiAvailability googleApiAvailability = GoogleApiAvailability.getInstance();
        int resultCode = googleApiAvailability.isGooglePlayServicesAvailable((Activity) ctx);
        if (resultCode != ConnectionResult.SUCCESS) {
            if (googleApiAvailability.isUserResolvableError(resultCode)) {
                // "user resolvable" means Google Play is available to download the last version of Play Services APK
                // This will open Google dialog fragment displaying the proper message depending on "resultCode"
                googleApiAvailability.showErrorDialogFragment((Activity) ctx, resultCode, Constants.PLAY_SERVICES_RESOLUTION_REQUEST);
                //ACRA.getErrorReporter().handleSilentException(new Exception("Google play Service Error!" + resultCode));
            } else {
                DebugLog.i("This device is not supported.");
                //Log.i(TAG, "This device is not supported.");
                //ACRA.getErrorReporter().handleSilentException(new Exception("Google play Service Unresolved Error!"));

                ((Activity) ctx).finish();
            }
            return false;
        }
        return true;
    }
Internally oogleApiAvailability.isGooglePlayServicesAvailable((Activity) ctx) uses application metadata "com.google.android.gms.version" to match with google play service version installed in device.

i have figured out using google play service code that 
before patching 
context.getPackageManager().getPackageInfo("com.google.android.gms", 64).versionCode
it returns correct value.
but after patching it return my application version code. so google play service code think i have lower version google play service installed and shows me a popup.

below is the application metadata information in manifest.
<application
        android:name=".MyApplication"
        android:configChanges="keyboardHidden|orientation"
        android:excludeFromRecents="true"
        android:hardwareAccelerated="false"
        android:icon="@drawable/logo_new"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:launchMode="singleTop"
        android:supportsRtl="true"
        android:theme="@style/Theme.HomeTheme">
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="8487000"
            tools:replace="android:value" />
.....
/>

i hope this information will help you finding the issue. if any thing required feel free to leave in comments and thanks for your reply.

**Comment by JackCho** [comment]
I think maybe this issue is fixed, please try with 

```groovy
classpath 'me.ele:amigo:0.6.2'
```

please tell us if this works

**Comment by JackCho** [comment]
@atulgoswami21 有空帮忙验证一下，问题是否已解决，并更新这个issue

**Comment by atulgoswami21** [comment]
Thanks a lot. Problem had resolved.
I have some queries.
Can i use google play distribution and amigo patch fix all together?
And Will future update using google play will work or not?
please clarify and thanks once again.

**Comment by JackCho** [comment]
目前是可以的，但是不排除被google play下架的风险，所有的hotfix方案都是和google play上架协议有冲突的，不能不考虑这种风险。但是技术上没有问题的，后面google play升级也不会对Amigo产生影响
