### ISSUE TITLE
每次启动app到主界面后自动退出

### ISSUE THREAD

**Issue by 320749903** [eleme/Amigo#183]
12-15 17:11:32.149 3839-4685/? E/ActivityManager: Invalid thumbnail dimensions: 576x576
12-15 17:11:32.151 4625-24001/? D/SplitWindowPolicy: updateActivityStateChanged: resumed=false, screenId=1, isScreenFull=true
12-15 17:11:32.153 4625-24001/? D/SplitWindowPolicy: topRunningActivity=ActivityInfo{38470a4b m.....KillSelfActivity}, taskId=32125, activityType=0, bIsSplit=false
12-15 17:11:32.155 1168-1168/? D/AmigoService: onHandleIntent: Intent { act=restart_main_process cmp=com.dxinfo.yanglao.family/me.ele.amigo.AmigoService }
12-15 17:11:32.155 3839-4723/? W/ActivityManager: Duplicate finish request for ActivityRecord{1e8e4eae u0 com.dxinfo.yanglao.family/.StartAppActivity t32125 f}
12-15 17:11:32.156 3839-4778/? W/ActivityManager: Duplicate finish request for ActivityRecord{2d3f17e3 u0 com.dxinfo.yanglao.family/.MainActivity t32125 f}
12-15 17:11:32.156 3574-3574/? I/Process: Sending signal. PID: 3574 SIG: 9
12-15 17:11:32.170 30094-30094/? I/[LGHome]EVENT: [Launcher.java:5846:onWindowFocusChanged()]onWindowFocusChanged() hasFocus true
12-15 17:11:32.170 30094-30094/? I/PhoneWindow: [setNavigationBarColor] color=0x 0
12-15 17:11:32.172 3839-4648/? W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@17076372 attribute=null, token = android.os.BinderProxy@55ef654
12-15 17:11:32.181 3186-3186/? V/DPM: |COMMON:COM| there are 1 file descriptor(s) with events pending
12-15 17:11:32.181 3186-3186/? V/DPM: |COMMON:COM| 1 events pending, handling 17 for 21
12-15 17:11:32.181 3186-3186/? I/DPM: |COMMON:COM| fd '21' sent HUP.
12-15 17:11:32.181 3839-4778/? D/LocationManagerService: Location listener died
12-15 17:11:32.181 3186-3186/? V/DPM: |COMMON:COM| DpmCom::removeComEventHandler fd 21
12-15 17:11:32.181 3839-4778/? I/LocationManagerService: remove 38a6736a
12-15 17:11:32.181 3186-3186/? V/DPM: |COMMON:COM| waiting on events (-1ms)
12-15 17:11:32.183 3839-4741/? D/GpsStatusListenerHelper: Remote Listener died: android.location.IGpsStatusListener$Stub$Proxy@2a9e43c3
12-15 17:11:32.185 3839-4071/? W/InputDispatcher: channel '25e72710 com.dxinfo.yanglao.family/com.dxinfo.yanglao.family.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-15 17:11:32.185 3839-4071/? E/InputDispatcher: channel '25e72710 com.dxinfo.yanglao.family/com.dxinfo.yanglao.family.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-15 17:11:32.188 3839-4814/? I/WindowState: WIN DEATH: Window{25e72710 u0 com.dxinfo.yanglao.family/com.dxinfo.yanglao.family.MainActivity}
12-15 17:11:32.188 3839-4814/? W/InputDispatcher: Attempted to unregister already unregistered input channel '25e72710 com.dxinfo.yanglao.family/com.dxinfo.yanglao.family.MainActivity (server)'
12-15 17:11:32.197 3839-4814/? D/InputDispatcher: Window went away: Window{25e72710 u0 com.dxinfo.yanglao.family/com.dxinfo.yanglao.family.MainActivity}
12-15 17:11:32.216 3839-4722/? I/ActivityManager: Process com.dxinfo.yanglao.family (pid 3574) has died
12-15 17:11:32.216 3839-4722/? W/ActivityManager: Scheduling restart of crashed service com.dxinfo.yanglao.family/.service.LocationService in 64000ms
12-15 17:11:32.219 3839-4722/? D/SplitWindowManager: Need to update ActivityRecord{2eaf0b4e u0 com.android.providers.downloads.ui/.DownloadList t32103} to ActivityStack{1f45e0fc stackId=1, 30 tasks}

删除重新安装app后，就正常了

**Comment by FtheGFW** [comment]
是指 patch 加载成功后进入主界面自动退出？请上传一下手机型号，rom，sdk 等信息

**Comment by 320749903** [comment]
LG-F350L
F350L20b, rooted

android 5.0.1
kernel 3.4.0

compileSdkVersion 25
buildToolsVersion "25.0.1"

minSdkVersion 15
targetSdkVersion 19

**Comment by JackCho** [comment]
@320749903 没有发现Amigo相关的日志信息，麻烦再重新一下，把更多的log贴上来

**Comment by twiceyuan** [comment]
也遇到相同的问题，日志只有下面这些

12-19 14:57:18.837 31404-31404/? I/art: Late-enabling -Xcheck:jni
12-19 14:57:18.907 31404-31404/com.twiceyuan.elemepatchdemo D/ProviderStub: onCreate
12-19 14:57:18.946 31404-31436/com.twiceyuan.elemepatchdemo W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
12-19 14:57:18.974 31404-31404/com.twiceyuan.elemepatchdemo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-19 14:57:19.038 31404-31458/com.twiceyuan.elemepatchdemo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-19 14:57:19.084 31404-31458/com.twiceyuan.elemepatchdemo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 09/02/15, 76f806e, Ibddc658e36
12-19 14:57:19.088 31404-31458/com.twiceyuan.elemepatchdemo I/OpenGLRenderer: Initialized EGL, version 1.4
12-19 14:57:19.209 31404-31436/com.twiceyuan.elemepatchdemo V/MD5: Calculated digest: 53bba5f4e16967422de3892a5095c8c2
12-19 14:57:19.210 31404-31436/com.twiceyuan.elemepatchdemo V/MD5: Provided digest: 53bba5f4e16967422de3892a5095c8c2
12-19 14:57:19.600 31404-31404/com.twiceyuan.elemepatchdemo I/Process: Sending signal. PID: 31404 SIG: 9

**Comment by twiceyuan** [comment]
发现问题了，是属性 
```
amigo {
    disable false //默认 false
}
```
错填为 true 导致的。

不过这个填 true 的话，应用程序也会启动后自己退出的行为是正常的么？

**Comment by JackCho** [comment]
对的，这个是正常的。为什么会这样呢，我介绍下原因。

Amigo plugin的工作之一就是把APP的application替换成`Amigo.class`，这样APP重新启动时Amigo时最先被调用，就能帮助完成预先处理工作。因为可能疏忽disable了amigo，application没有被替换，这样APP在`KillSelf`后，就无法完成重启了，上面同学也check下是否这个原因造成的 @320749903

**Comment by twiceyuan** [comment]
@JackCho 原来如此，感谢耐心讲解！

那么实践中是不是最好补丁的版本号要高于原始包的版本号？

比如原始包版本号为 1，先上传了一个补丁包版本也为 1，在开发第二个补丁包（版本还是 1）的情况下，即使 disable 了 amigo，应用也会在每次启动时 apply 了第一个补丁？

**Comment by JackCho** [comment]
对的，是这个意思。建议补丁版本号要比host大，至少一样大，Amigo逻辑就是如此的

**Comment by 320749903** [comment]
apply plugin: 'com.android.application'

apply plugin: 'me.ele.amigo'
//开发阶段可选不启用
amigo {
    disable true //默认 false
}

android {
...
}

是这个原因，发布时忘记改这个设置了。

怎么写可以使设置只在开发模式下起作用？

**Comment by JackCho** [comment]
@320749903 这个你可以通过自定义在本地的`apply from: ${your_custom.gradle}`去完成，或者你自己手动进行修改
