### ISSUE TITLE
修复后进入某个页面crash

### ISSUE THREAD

**Issue by wznshuai** [eleme/Amigo#184]
日志:

W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx.xxxx/com.xxx.xxx.xxxx.activity.WebActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class android.webkit.WebView
 W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
 W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
 W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:171)
 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
 W/System.err:     at android.os.Looper.loop(Looper.java:194)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5468)
 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
 W/System.err:     at dalvik.system.NativeStart.main(Native Method)
 W/System.err: Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class  
                   android.webkit.WebView
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
 W/System.err:     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
 W/System.err:     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
 W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
 W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
 W/System.err:     at com.xxx.xxx.xxxx.fragment.WebFragment.onCreateView(WebFragment.java:124)
 W/System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
 W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
 W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
 W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
 W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
 W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
 W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
 W/System.err:     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
 W/System.err:     at com.trello.rxlifecycle.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:52)
 W/System.err:     at com.xxx.xxx.xxxx.activity.WebActivity.onStart(WebActivity.java)
 W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
 W/System.err:     at android.app.Activity.performStart(Activity.java:5221)
 W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2350)
 W/System.err: 	... 11 more
 W/System.err: Caused by: java.lang.reflect.InvocationTargetException
 W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
 W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
 W/System.err: 	... 31 more
 W/System.err: Caused by: java.lang.NullPointerException
 W/dalvikvm: threadid=70: thread exiting with uncaught exception (group=0x40f8f978)
 W/dalvikvm: threadid=70: uncaught exception occurred
 W/System.err: java.lang.RuntimeException: An error occured while executing doInBackground()
 W/System.err:     at android.os.AsyncTask$3.done(AsyncTask.java:299)
 W/System.err:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 W/System.err:     at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 W/System.err:     at java.lang.Thread.run(Thread.java:838)
 W/System.err: Caused by: java.lang.NullPointerException
 W/System.err:     at me.ele.amigo.hook.IPackageManagerHookHandle$getPackageInfo.afterInvoke(IPackageManagerHookHandle.java:93)
 W/System.err:     at me.ele.amigo.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:38)
 W/System.err:     at 	at me.ele.amigo.hook.ProxyHook.invoke(ProxyHook.java:31)
 W/System.err:     at $Proxy1.getPackageInfo(Native Method)
 W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:85)
 W/System.err:     at android.webkit.WebViewClassic.init(WebViewClassic.java:1402)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:522)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:492)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:472)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:461)
 W/System.err: 	... 34 more
 W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
 W/System.err: me.ele.amigo.hook.IPackageManagerHookHandle$getPackageInfo.afterInvoke(IPackageManagerHookHandle.java:93)
 W/System.err:     at me.ele.amigo.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:38)
 W/System.err:     at me.ele.amigo.hook.ProxyHook.invoke(ProxyHook.java:31)
 W/System.err:     at $Proxy1.getPackageInfo(Native Method)
 W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:85)
 W/System.err:     at android.webkit.WebViewClassic$2.doInBackground(WebViewClassic.java:1840)
 W/System.err:     at android.webkit.WebViewClassic$2.doInBackground(WebViewClassic.java:1832)
 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
 W/System.err: 	... 4 more
 W/dalvikvm: threadid=70: calling UncaughtExceptionHandler
 W/dalvikvm: threadid=70: calling UncaughtExceptionHandler done
 E/BluetoothAdapter: getDefaultAdapter()
 E/BluetoothAdapter: BluetoothAdapter(IBluetoothManager managerService)
 E/BluetoothAdapter: getDefaultAdapter()
 W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx.xxxx/ 
  					com.xxx.xxx.xxxx.activity.WebActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class android.webkit.WebView
 W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
 W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
 W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:171)
 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
 W/System.err:     at android.os.Looper.loop(Looper.java:194)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5468)
 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
 W/System.err:     at dalvik.system.NativeStart.main(Native Method)
 W/System.err: Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class 		 
                     android.webkit.WebView
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
 W/System.err:     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
 W/System.err:     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
 W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
 W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
 W/System.err:     at com.xxx.xxx.xxxx.fragment.WebFragment.onCreateView(WebFragment.java:124)
 W/System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
 W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
 W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
 W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
 W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
 W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
 W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
 W/System.err:     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
 W/System.err:     at com.trello.rxlifecycle.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:52)
 W/System.err:     at com.xxx.xxx.xxxx.activity.WebActivity.onStart(WebActivity.java)
 W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
 W/System.err:     at android.app.Activity.performStart(Activity.java:5221)
 W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2350)
 W/System.err: 	... 11 more
 W/System.err: Caused by: java.lang.reflect.InvocationTargetException
 W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
 W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
               
               [ 12-16 10:19:42.924   175:0x276 I/         ]
               MirrorAudioService::onAudioBuffer: outBuffSize=4460 size=4460 outConverterBytes=0
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
 W/System.err: 	... 31 more
 W/System.err: Caused by: java.lang.NullPointerException
 W/System.err:     at me.ele.amigo.hook.IPackageManagerHookHandle$getPackageInfo.afterInvoke(
                    IPackageManagerHookHandle.java:93)              
 W/System.err:     at me.ele.amigo.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:38)
 W/System.err:     at me.ele.amigo.hook.ProxyHook.invoke(ProxyHook.java:31)
 W/System.err:     at $Proxy1.getPackageInfo(Native Method)
 W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:85)
 W/System.err:     at android.webkit.WebViewClassic.init(WebViewClassic.java:1402)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:522)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:492)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:472)
 W/System.err:     at android.webkit.WebView.<init>(WebView.java:461)
 W/System.err: 	... 34 more

0.6.1版本 手机华为 G750-T01   版本4.2.2 华为版本 Emotion 2.0

@JackCho @FtheGFW

**Comment by FtheGFW** [comment]
Thanks for your information, we are working on this.

**Comment by JackCho** [comment]
I think maybe this issue is fixed, please try with 

```groovy
classpath 'me.ele:amigo:0.6.2'
```

please tell us if this works

**Comment by JackCho** [comment]
@wznshuai 有空帮忙验证一下，问题是否已解决，并更新这个issue

**Comment by wznshuai** [comment]
哦 好哒 明天我看一下 @JackCho 另外正确得到当前运行APK的方式是什么呢？要做patch合成，我从patchApk1 打补丁 生成patchApk2的时候 合成的apk不对，应该是姿势不对 拿到的是原始的apk去合成了 拿到的并不是patchApk1，Amigo有相应的工具类吗

**Comment by wznshuai** [comment]
依然会crash

12-20 13:46:10.868 12921-13064/? W/dalvikvm: threadid=54: thread exiting with uncaught exception (group=0x41bc3978)
12-20 13:46:10.868 12921-13064/? W/dalvikvm: threadid=54: uncaught exception occurred
12-20 13:46:10.869 12921-13064/? W/System.err: java.lang.RuntimeException: An error occured while executing doInBackground()
12-20 13:46:10.870 12921-13064/? W/System.err:     at android.os.AsyncTask$3.done(AsyncTask.java:299)
12-20 13:46:10.871 12921-13064/? W/System.err:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
12-20 13:46:10.871 12921-13064/? W/System.err:     at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
12-20 13:46:10.871 12921-13064/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:239)
12-20 13:46:10.871 12921-13064/? W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
12-20 13:46:10.871 12921-13064/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
12-20 13:46:10.871 12921-13064/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
12-20 13:46:10.871 12921-13064/? W/System.err:     at java.lang.Thread.run(Thread.java:838)
12-20 13:46:10.871 12921-13064/? W/System.err: Caused by: java.lang.NullPointerException
12-20 13:46:10.871 12921-12921/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41bc3978)
12-20 13:46:10.871 12921-12921/? W/dalvikvm: threadid=1: uncaught exception occurred
12-20 13:46:10.872 12921-12921/? W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx.xxxx/com.xxx.xxx.xxxx.activity.WebActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class android.webkit.WebView
12-20 13:46:10.873 12921-12921/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
12-20 13:46:10.873 12921-12921/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
12-20 13:46:10.874 12921-12921/? W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:171)
12-20 13:46:10.874 12921-12921/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
12-20 13:46:10.874 12921-12921/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
12-20 13:46:10.874 12921-12921/? W/System.err:     at android.os.Looper.loop(Looper.java:194)
12-20 13:46:10.874 12921-12921/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5468)
12-20 13:46:10.874 12921-12921/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-20 13:46:10.874 12921-12921/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
12-20 13:46:10.874 12921-12921/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
12-20 13:46:10.875 12921-12921/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
12-20 13:46:10.880 12921-12921/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-20 13:46:10.881 12921-12921/? W/System.err: Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class android.webkit.WebView
12-20 13:46:10.882 13048-13048/? W/asset: AssetManager-->addDefaultAssets CIP path not exsit!
12-20 13:46:10.894 12921-12921/? W/System.err:     at 	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
12-20 13:46:10.895 12921-12921/? W/System.err:     at me.ele.amigo.hook.IPackageManagerHookHandle$getPackageInfo.afterInvoke(IPackageManagerHookHandle.java:94)com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
12-20 13:46:10.895 12921-12921/? W/System.err:     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
12-20 13:46:10.895 12921-12921/? W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
12-20 13:46:10.896 12921-12921/? W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
12-20 13:46:10.896 12921-12921/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
12-20 13:46:10.896 12921-12921/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
12-20 13:46:10.896 12921-12921/? W/System.err:     at com.xxx.xxx.xxxx.fragment.WebFragment.onCreateView(WebFragment.java:124)
12-20 13:46:10.896 12921-12921/? W/System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
12-20 13:46:10.897 12921-12921/? W/System.err:     at android.support.v4.app.af.a(FragmentManager.java:1108)
12-20 13:46:10.897 12921-12921/? W/System.err:     at android.support.v4.app.af.a(FragmentManager.java:1290)
12-20 13:46:10.897 12921-12921/? W/System.err:     at android.support.v4.app.t.run(BackStackRecord.java:801)
12-20 13:46:10.897 12921-12921/? W/System.err:     at android.support.v4.app.af.j(FragmentManager.java:1677)
12-20 13:46:10.897 12921-12921/? W/System.err:     at android.support.v4.app.ac.r(FragmentController.java:388)
12-20 13:46:10.897 12921-12921/? W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
12-20 13:46:10.898 12921-12921/? W/System.err:     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
12-20 13:46:10.898 12921-12921/? W/System.err:     at com.trello.rxlifecycle.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:52)
12-20 13:46:10.898 12921-13064/? W/System.err: 	at 
12-20 13:46:10.898 12921-12921/? W/System.err:     at com.xxx.xxx.xxxx.activity.WebActivity.onStart(WebActivity.java)
12-20 13:46:10.898 12921-12921/? W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
12-20 13:46:10.899 12921-12921/? W/System.err:     at me.ele.amigo.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:38)android.app.Activity.performStart(Activity.java:5221)
12-20 13:46:10.899 12921-12921/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2350)
12-20 13:46:10.899 12921-12921/? W/System.err: 	... 11 more
12-20 13:46:10.899 12921-13064/? W/System.err: Caused by: 
12-20 13:46:10.899 12921-12921/? W/System.err: java.lang.reflect.InvocationTargetException
12-20 13:46:10.901 12921-13064/? W/System.err: 	at me.ele.amigo.hook.ProxyHook.invoke(ProxyHook.java:31)	at 
12-20 13:46:10.902 12921-12921/? W/System.err: java.lang.reflect.Constructor.constructNative(Native Method)
12-20 13:46:10.902 12921-12921/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
12-20 13:46:10.902 12921-12921/? W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
12-20 13:46:10.902 12921-12921/? W/System.err: 	... 31 more
12-20 13:46:10.903 12921-12921/? W/System.err: Caused by: java.lang.NullPointerException
12-20 13:46:10.904 12921-13064/? W/System.err:     at $Proxy1.getPackageInfo(Native Method)
12-20 13:46:10.904 12921-13064/? W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:85)
12-20 13:46:10.904 12921-13064/? W/System.err:     at android.webkit.WebViewClassic$2.doInBackground(WebViewClassic.java:1840)
12-20 13:46:10.904 12921-13064/? W/System.err:     at android.webkit.WebViewClassic$2.doInBackground(WebViewClassic.java:1832)
12-20 13:46:10.905 12921-13064/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
12-20 13:46:10.905 12921-13064/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
12-20 13:46:10.905 12921-13064/? W/System.err: 	... 4 more
12-20 13:46:10.905 13048-13048/? E/TouchPal: ROM build in
12-20 13:46:10.905 12921-13064/? W/dalvikvm: threadid=54: calling UncaughtExceptionHandler
12-20 13:46:10.905 12921-12921/? W/System.err:     at me.ele.amigo.hook.IPackageManagerHookHandle$getPackageInfo.afterInvoke(IPackageManagerHookHandle.java:94)
12-20 13:46:10.905 12921-12921/? W/System.err:     at me.ele.amigo.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:38)
12-20 13:46:10.906 12921-12921/? W/System.err:     at me.ele.amigo.hook.ProxyHook.invoke(ProxyHook.java:31)
12-20 13:46:10.906 12921-12921/? W/System.err:     at $Proxy1.getPackageInfo(Native Method)
12-20 13:46:10.906 12921-12921/? W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:85)
12-20 13:46:10.906 12921-12921/? W/System.err:     at android.webkit.WebViewClassic.init(WebViewClassic.java:1402)
12-20 13:46:10.906 12921-12921/? W/System.err:     at android.webkit.WebView.<init>(WebView.java:522)
12-20 13:46:10.906 12921-12921/? W/System.err:     at android.webkit.WebView.<init>(WebView.java:492)
12-20 13:46:10.906 12921-12921/? W/System.err:     at android.webkit.WebView.<init>(WebView.java:472)
12-20 13:46:10.907 12921-12921/? W/System.err:     at android.webkit.WebView.<init>(WebView.java:461)
12-20 13:46:10.907 12921-12921/? W/System.err: 	... 34 more
12-20 13:46:10.907 12921-12921/? W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
12-20 13:46:10.907 12921-12921/? W/dalvikvm: threadid=1: calling UncaughtExceptionHandler done

**Comment by JackCho** [comment]
try with 

```groovy
classpath 'me.ele:amigo:0.6.3'
```

**Comment by wznshuai** [comment]
fixed
