### ISSUE TITLE
me.ele.amigo.utils.FileUtils

### ISSUE THREAD

**Issue by wsigang** [eleme/Amigo#187]
java.lang.RuntimeException: Unable to create application me.ele.amigo.Amigo: java.lang.RuntimeException: java.lang.NoClassDefFoundError: me.ele.amigo.utils.FileUtils

**Comment by FtheGFW** [comment]
麻烦重新上传一下完整的 crsh stacktrace @wsgang

**Comment by JackCho** [comment]
no more info, close this temporarily
