### ISSUE TITLE
IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data

### ISSUE THREAD

**Issue by atulgoswami21** [eleme/Amigo#188]
I have added a new provider to fix Uri permission in Nouget.
```xml
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.bizzypulse.bizzypulse.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
```
and used
 ```java
Intent cameraIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT,
                                    FileProvider.getUriForFile(host, host.getApplicationContext().getPackageName() + ".provider", createImageFile()));
                            getView().startActivityForResult(cameraIntent, CAMERA_REQUEST);
```
in place of

```java
Intent cameraIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT,Uri.fromFile(createImageFile()));
getView().startActivityForResult(cameraIntent, CAMERA_REQUEST);
```

and also added provider_paths in xml folder with content

```xml
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
<external-path name="external_files" path="."/>
</paths>
```

but after applying patch it gives me IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data.

**Comment by FtheGFW** [comment]
I couldn't reproduce the problem you mentioned above, would you provide us with more details,  like did you use [amigo-sdk](https://amigo.ele.me/#/wiki/add-sdk), and the stacktraces

(Note: adding new FileProvider just into patch apk is not supported currently)

**Comment by redevill** [comment]
For what it is worth - I noticed that the MinSdkVersion affects the existence of the error in my case.

**Comment by irfaan008** [comment]
@atulgoswami21 only problem with your code is, the authority name doesn't end with extension '.fileprovider' . It seems weird but not ending the file provider authority name with ".fileprovider" throws this error.

**Comment by JackCho** [comment]
seems nothing to do with Amigo

**Comment by roslynn** [comment]
I just spent ages on the same issue. Some people suggested typos (no typos there) some mentioned other possibilities like wrong folder or advising techniques of modifying config.xml or checking sdk versions....
The thing that was missing for me was that this stupid "provider_paths.xml" Build Action was set to _Content_ and not to _AndroidResource_ hence it was never copied during compilation hence it was missing and never found...

I am sure this is the case in this scenario as well... It might be a bit too late for @atulgoswami21 but for future generations running into the same stupid mistake like me - there you go :)

**Comment by sayedtalha124** [comment]
Add this to your proguard-rules 
#-keep class com.shockwave.**

**Comment by gcantoni** [comment]
> I just spent ages on the same issue. Some people suggested typos (no typos there) some mentioned other possibilities like wrong folder or advising techniques of modifying config.xml or checking sdk versions....
> The thing that was missing for me was that this stupid "provider_paths.xml" Build Action was set to _Content_ and not to _AndroidResource_ hence it was never copied during compilation hence it was missing and never found...
> 
> I am sure this is the case in this scenario as well... It might be a bit too late for @atulgoswami21 but for future generations running into the same stupid mistake like me - there you go :)

What do you mean exactly? I'm the facing the same issue.

**Comment by roslynn** [comment]
If you select your file in the Solution Explorer and right click - select Properties (default shortcut is F4 key) then on the revealed Properties Panel you would see various configurations, one of them is a "Build Action" which for me was pre-set to "Content" value. When I flipped it to "Android Resource" and save and build the application started to work.

Try it out, maybe it is same for you :)
