### ISSUE TITLE
更新完成后，使用微信分享接口Crash

### ISSUE THREAD

**Issue by pengzhuo** [eleme/Amigo#191]
设备：Moto G
系统：Android 5.1

12-22 17:10:40.947 14093-14093/? D/HookedMethodHandler: doHookInner beforeInvoke cost 0 ms
12-22 17:10:40.949 297-1038/? E/FastThread: did not receive expected priority boost
12-22 17:10:40.951 14093-14093/? I/HookedMethodHandler: doHookInner invoke cost 3 ms
12-22 17:10:40.953 297-1038/? V/msm8974_platform: platform_get_output_snd_device: enter: output devices(0x2)
12-22 17:10:40.953 297-1038/? V/msm8974_platform: platform_get_output_snd_device: exit: snd_device(speaker)
12-22 17:10:40.953 297-1038/? D/audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
12-22 17:10:40.953 297-1038/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
12-22 17:10:40.953 297-1038/? V/msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)
12-22 17:10:40.962 14093-14093/? D/AndroidRuntime: Shutting down VM
                                                   
                                                   
                                                   --------- beginning of crash
12-22 17:10:40.964 14093-14093/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.pengz.kdsc, PID: 14093
                                                   java.lang.NullPointerException: Attempt to write to field 'int android.content.pm.PackageInfo.versionCode' on a null object reference
                                                       at me.ele.amigo.hook.IPackageManagerHookHandle$getPackageInfo.afterInvoke(Unknown Source)
                                                       at me.ele.amigo.hook.HookedMethodHandler.doHookInner(Unknown Source)
                                                       at me.ele.amigo.hook.ProxyHook.invoke(Unknown Source)
                                                       at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                       at $Proxy1.getPackageInfo(Unknown Source)
                                                       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:106)
                                                       at com.tencent.mm.sdk.openapi.WXApiImplComm.validateAppSignatureForPackage(Unknown Source)
                                                       at com.tencent.mm.sdk.openapi.WXApiImplV10.registerApp(Unknown Source)
                                                       at com.pengz.kdsc.c.b.<init>(Unknown Source)
                                                       at com.pengz.kdsc.c.b.a(Unknown Source)
                                                       at com.pengz.kdsc.view.MainActivity$3.onClick(Unknown Source)
                                                       at android.view.View.performClick(View.java:4785)
                                                       at android.view.View$PerformClick.run(View.java:19884)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                   
                                                   
                                                   --------- beginning of system
12-22 17:10:40.967 857-1413/? W/ActivityManager:   Force finishing activity 1 com.pengz.kdsc/.view.MainActivity
12-22 17:10:40.968 857-1413/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:40.969 857-1413/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.054 857-880/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.054 857-880/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.063 857-880/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.063 857-880/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.067 857-18173/? I/OpenGLRenderer: Initialized EGL, version 1.4
12-22 17:10:41.137 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.137 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.143 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.143 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.310 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.310 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.439 857-1262/? V/AlarmManager: sending alarm {3b208913 type 2 *walarm*:com.android.server.task.controllers.BatteryController.ACTION_CHARGING_STABLE}
12-22 17:10:41.445 857-1262/? V/AlarmManager: sending alarm {30c0727c type 1 *alarm*:com.platform.pushservice}
12-22 17:10:41.454 857-1262/? V/AlarmManager: sending alarm {28458883 type 3 *alarm*:com.google.android.gms/.lockbox.LockboxAlarmReceiver}
12-22 17:10:41.455 857-857/? V/AlarmManager: done {3b208913, *walarm*:com.android.server.task.controllers.BatteryController.ACTION_CHARGING_STABLE} [17ms]
12-22 17:10:41.456 857-857/? V/AlarmManager: done {30c0727c, *alarm*:com.platform.pushservice} [18ms]
12-22 17:10:41.457 857-857/? V/AlarmManager: done {28458883, *alarm*:com.google.android.gms/.lockbox.LockboxAlarmReceiver} [18ms]
12-22 17:10:41.476 259-782/? I/SFPerfTracer:      triggers: (rate: 1:30) (5562760 sw vsyncs) (0 skipped) (27:4586573 vsyncs) (29:10189840)
12-22 17:10:41.503 857-880/? W/ProcessCpuTracker: Skipping unknown process pid 14149
12-22 17:10:41.506 857-880/? W/ProcessCpuTracker: Skipping unknown process pid 14150
12-22 17:10:41.507 857-880/? W/ProcessCpuTracker: Skipping unknown process pid 14153
12-22 17:10:41.508 857-880/? W/ProcessCpuTracker: Skipping unknown process pid 14164
12-22 17:10:41.511 857-880/? W/ActivityManager: Activity pause timeout for ActivityRecord{157d457c u0 com.pengz.kdsc/.view.MainActivity t1357 f}
12-22 17:10:41.516 857-880/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.516 857-880/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.532 857-1707/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.532 857-1707/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.565 857-1355/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.565 857-1355/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.631 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.631 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.638 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.638 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.638 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.638 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.643 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.644 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.646 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.646 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.663 259-259/? I/SFPerfTracer:      triggers: (rate: 71:8470) (compose: 0:35) (post: 0:6) (render: 47:698) (4:651982 frames) (5:709496)
12-22 17:10:41.663 259-259/? D/SFPerfTracer:        layers: (5:14) (FocusedStackFrame (0xb7561570): 1:2292)* (DimLayer (0xb7563978): 0:245) (DimLayer (0xb752d558): 0:80)* (DimLayer (0xb7531038): 0:1215)* (DimLayer (0xb7533648): 0:536)* (StatusBar (0xb7516fa0): 0:45974) (com.android.systemui.ImageWallpaper (0xb757e160): 0:1130)* (NavigationBar (0xb759ebb8): 0:1990) (com.android.launcher/com.android.launcher2.Launcher (0xb7583150): 0:168)- (Starting com.pengz.kdsc (0xb7512f58): 0:30)- (com.pengz.kdsc/com.pengz.kdsc.view.MainActivity (0xb7578ca8): 0:7) (Toast (0xb7583150): 0:65)- (Application Error: com.pengz.kdsc (0xb7512f58): 0:16) (com.android.launcher/com.android.launcher2.Launcher (0xb7583150): 5:5)* 
12-22 17:10:41.896 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.896 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.899 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.899 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.901 857-880/? I/ActivityManager: Killing 13659:com.google.android.partnersetup/u0a24 (adj 15): empty #7
12-22 17:10:41.938 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:41.938 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:41.946 857-1274/? E/WifiStateMachine: calculateWifiScore() report new score 56
12-22 17:10:41.947 857-1278/? D/ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 103] to 56
12-22 17:10:41.947 857-1278/? D/ConnectivityService: rematching NetworkAgentInfo [WIFI () - 103]
12-22 17:10:41.947 857-1278/? D/ConnectivityService: Network NetworkAgentInfo [WIFI () - 103] was already satisfying request 1. No change.
12-22 17:10:41.947 857-1278/? D/ConnectivityService: notifyType AVAILABLE for NetworkAgentInfo [WIFI () - 103]
12-22 17:10:41.950 24414-31837/? D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
12-22 17:10:41.950 1343-1867/? D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
12-22 17:10:41.956 1343-1343/? I/MotoNetwCtrlr: onReceive: Received intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
12-22 17:10:41.956 1343-1343/? I/MotoNetwCtrlr.MotoWifiSignalCtrlr: handleBroadcast: Entered: Intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
12-22 17:10:41.956 1343-1343/? I/MotoNetwCtrlr.MotorolaWifiSignalController: isDirty: returns false
12-22 17:10:41.956 1343-1343/? I/MotoNetwCtrlr.MotoWifiSignalCtrlr: handleBroadcast: Completed
12-22 17:10:41.956 1343-1343/? I/MotoNetwCtrlr: onReceive: Completed intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
12-22 17:10:42.096 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:42.096 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:42.100 857-901/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
12-22 17:10:42.100 857-901/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
12-22 17:10:42.460 857-1274/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=1.50 rxSuccessRate=1.13 targetRoamBSSID=any RSSI=-66
12-22 17:10:42.461 857-1274/? E/WifiStateMachine: startDelayedScan send -> 5995 milli 20000
12-22 17:10:42.461 857-1274/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN with age=240051 interval=341718 maxinterval=300000
12-22 17:10:42.461 857-1274/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN full=false
12-22 17:10:42.525 1343-1343/? W/ResourceType: No package identifier when getting value for resource number 0x00000000
12-22 17:10:42.526 1343-1343/? W/PackageManager: Failure retrieving resources for com.pengz.kdsc: Resource ID #0x0
12-22 17:10:44.176 297-1039/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
12-22 17:10:44.978 1343-1343/? I/MotoNetwCtrlr: onReceive: Received intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
12-22 17:10:44.978 1343-1343/? I/MotoNetwCtrlr.MotoWifiSignalCtrlr: handleBroadcast: Entered: Intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
12-22 17:10:44.978 1343-1343/? I/MotoNetwCtrlr.MotorolaWifiSignalController: isDirty: returns false
12-22 17:10:44.978 1343-1343/? I/MotoNetwCtrlr.MotoWifiSignalCtrlr: handleBroadcast: Completed
12-22 17:10:44.979 1343-1343/? I/MotoNetwCtrlr: onReceive: Completed intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
01-01 00:00:00.000 0-0/? E/Internal: device 'TA89902GXU' not found

**Comment by JackCho** [comment]
please use `me.ele:amigo:0.6.3`, and try again

this should be fixed

**Comment by pengzhuo** [comment]
感谢，问题已解决！
