### ISSUE TITLE
Package manager has died

### ISSUE THREAD

**Issue by jason1114** [eleme/Amigo#192]
After I apply the patch, the Application restart and crash:

Here is the log:

l E/Amigo: #onCreate working checksum: 517328880
12-26 18:57:01.405 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->2786663950, checksum--->2786663950
12-26 18:57:01.405 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1406111816, checksum--->1406111816
12-26 18:57:01.405 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1544702662, checksum--->1544702662
12-26 18:57:01.406 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->813114639, checksum--->813114639
12-26 18:57:01.406 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->2910170220, checksum--->2910170220
12-26 18:57:01.406 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1801633650, checksum--->1801633650
12-26 18:57:01.407 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->2529574348, checksum--->2529574348
12-26 18:57:01.407 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->3452455573, checksum--->3452455573
12-26 18:57:01.407 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1325399336, checksum--->1325399336
12-26 18:57:01.408 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1070691864, checksum--->1070691864
12-26 18:57:01.408 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->282344872, checksum--->282344872
12-26 18:57:01.408 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1495017425, checksum--->1495017425
12-26 18:57:01.408 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->3490315611, checksum--->3490315611
12-26 18:57:01.409 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->2645135176, checksum--->2645135176
12-26 18:57:01.409 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1808888460, checksum--->1808888460
12-26 18:57:01.409 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->3014940152, checksum--->3014940152
12-26 18:57:01.410 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->1739308871, checksum--->1739308871
12-26 18:57:01.410 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->75590813, checksum--->75590813
12-26 18:57:01.410 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->409785304, checksum--->409785304
12-26 18:57:01.411 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->3735869817, checksum--->3735869817
12-26 18:57:01.412 18071-18071/com.xxx.yyy E/me.ele.amigo.PatchChecker: savedChecksum-->3433392412, checksum--->3433392412
12-26 18:57:01.527 18071-18071/com.xxx.yyy E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 128)
12-26 18:57:01.531 18071-18071/com.xxx.yyy E/Amigo: installAndHook fails with patch java.lang.reflect.InvocationTargetException
12-26 18:57:01.619 18071-18071/com.xxx.yyy E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 128)
12-26 18:57:01.692 18071-18097/com.xxx.yyy E/Posix: [Posix_connect Debug]Process com.xxx.yyy :443 
12-26 18:57:01.709 18071-18097/com.xxx.yyy E/NativeCrypto: ssl=0xf3e62140 cert_verify_callback x509_store_ctx=0xee881e6c arg=0x0
12-26 18:57:01.709 18071-18097/com.xxx.yyy E/NativeCrypto: ssl=0xf3e62140 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
12-26 18:57:01.778 18071-18104/com.xxx.yyy E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
12-26 18:57:01.804 18071-18104/com.xxx.yyy E/Posix: [Posix_connect Debug]Process com.xxx.yyy :443 
12-26 18:57:01.823 18071-18104/com.xxx.yyy E/NativeCrypto: ssl=0xf3e63f40 cert_verify_callback x509_store_ctx=0xd64dddec arg=0x0
12-26 18:57:01.823 18071-18104/com.xxx.yyy E/NativeCrypto: ssl=0xf3e63f40 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_ECDSA
12-26 18:57:02.272 18071-18147/com.xxx.yyy E/Posix: [Posix_connect Debug]Process com.xxx.yyy :443 
12-26 18:57:02.294 18071-18147/com.xxx.yyy E/NativeCrypto: ssl=0xf3e64080 cert_verify_callback x509_store_ctx=0xd5717f9c arg=0x0
12-26 18:57:02.294 18071-18147/com.xxx.yyy E/NativeCrypto: ssl=0xf3e64080 cert_verify_callback calling verifyCertificateChain authMethod=DHE_RSA
12-26 18:57:02.332 18071-18157/com.xxx.yyy E/Posix: [Posix_connect Debug]Process com.xxx.yyy :80 
12-26 18:57:02.341 18071-18071/com.xxx.yyy E/SysUtils: ApplicationContext is null in ApplicationStatus
12-26 18:57:02.366 18071-18071/com.xxx.yyy E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
12-26 18:57:02.366 18071-18071/com.xxx.yyy E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
12-26 18:57:02.430 18071-18071/com.xxx.yyy E/DataReductionProxySettingListener: No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
12-26 18:57:02.434 18071-18195/com.xxx.yyy E/chromium: [ERROR:unix_domain_server_socket_posix.cc(106)] Not implemented reached in virtual int net::UnixDomainServerSocket::GetLocalAddress(net::IPEndPoint*) const
12-26 18:57:02.556 18071-18197/com.xxx.yyy E/thinkive: com.android.thinkive.framework.config.ConfigManager.clear(): clear !!!!!!!!!!!!!!
12-26 18:57:02.774 1017-1017/? E/NotificationService: Not posting notification without small icon: Notification(pri=0 contentView=null headsUpContentView=null bigContentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
12-26 18:57:02.774 1017-1017/? E/NotificationService: WARNING: In a future release this will crash the app: com.xxx.yyy
12-26 18:57:02.777 1017-1017/? E/NotificationService: Not posting notification without small icon: Notification(pri=0 contentView=null headsUpContentView=null bigContentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
12-26 18:57:02.777 1017-1017/? E/NotificationService: WARNING: In a future release this will crash the app: com.xxx.yyy
12-26 18:57:03.802 1017-1219/? E/WifiStateMachine: wifiLinkStatics=
                                                   Failed=548486991872 Retry=2 MultipleRetry=6869191503434106198 ACKFailure=9232388042942056450 FCSError=0 tx_ok=0 rx_ok=0
12-26 18:57:03.803 1017-1219/? E/WifiStateMachine: calculateWifiScore not update currentConfiguration visibility
12-26 18:57:05.225 318-635/? E/MAL-Daemon: [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x6
12-26 18:57:05.326 1017-1017/? E/NotificationService: Not posting notification without small icon: Notification(pri=0 contentView=null headsUpContentView=null bigContentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
12-26 18:57:05.326 1017-1017/? E/NotificationService: WARNING: In a future release this will crash the app: com.xxx.yyy

**Here is where the problem happens:**

12-26 18:57:01.527 18071-18071/com.ect888.protal E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 128)
12-26 18:57:01.531 18071-18071/com.ect888.protal E/Amigo: installAndHook fails with patch java.lang.reflect.InvocationTargetException
12-26 18:57:01.619 18071-18071/com.ect888.protal E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 128)

Then i found the method where the exception is thrown:

    private void runPatchApk(String checksum) throws LoadPatchApkException {
        try {
            if (isPatchApkFirstRun(checksum) || !isOptedDexExists(checksum)) {
                PatchInfoUtil.updateDexFileOptStatus(this, checksum, false);
                releasePatchApk(checksum);
            } else {
                PatchChecker.checkDexAndSo(this, checksum);
            }

            AmigoClassLoader classLoader = AmigoClassLoader.newInstance(this, checksum);
            Object newAmigoInstance = null;
            try {
                Class<?> clazz = classLoader.loadClass(Amigo.class.getName());
                newAmigoInstance = clazz.newInstance();
                invokeMethod(newAmigoInstance, "attach", getBaseContext());
                invokeMethod(newAmigoInstance, "init");
                invokeMethod(newAmigoInstance, "installAndHook", checksum, classLoader);
                Log.i(TAG, "installAndHook successfully with patch");
            } catch (Exception e) {
                e.printStackTrace();
                Log.e(TAG, String.format("installAndHook fails with patch %s", e));
                if (newAmigoInstance != null) {
                    try {
                        invokeMethod(newAmigoInstance, "revertAll");
                        Log.i(TAG, "revertAll newAmigoInstance successfully");
                    } catch (Exception ee) {
                        ee.printStackTrace();
                        Log.i(TAG, "revertAll newAmigoInstance fails");
                    }
                }
                installAndHook(checksum, classLoader);
                Log.i(TAG, "installAndHook successfully with host");
            }
        } catch (Exception e) {
            throw new LoadPatchApkException(e);
        }
    }

And actuallly the error occurs at ActivityFinder#getAppActivities

    public static ActivityInfo[] getAppActivities(Context context) {
        if (sHostActivities != null) {
            return sHostActivities;
        }

        try {
            PackageManager pm = context.getPackageManager();
            /*
             * Notice :
             * will not return the activity-info of a component which is declared disabled in
             * manifest and has never been set to enabled state dynamically.
            */
            PackageInfo info =
                    pm.getPackageInfo(context.getPackageName(), PackageManager.GET_ACTIVITIES |
                            PackageManager.GET_META_DATA);
            return sHostActivities = info.activities;
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }
        return null;
    }

This line throws exception:
`PackageInfo info =
                    pm.getPackageInfo(context.getPackageName(), PackageManager.GET_ACTIVITIES |
                            PackageManager.GET_META_DATA);`

android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died

Package manager has died

**Comment by FtheGFW** [comment]
Weird, Amigo should catch the DeadObjectException raised from PackageManager#getPackageInfo in the process of applying a patch as your described above, and just run the original application.
BTW, Can you re-produce this problem on other phones or emulators ? @jason1114

**Comment by JackCho** [comment]
no more info here, seems nothing to do with Amigo
