### ISSUE TITLE
Error:A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by mengsuwen** [eleme/Amigo#194]
Could not find method RuntimeException() for arguments [Sorry, instant run conflicts with Amigo, so please disable Instant Run] on object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

请大神指教，谢谢

**Comment by JackCho** [comment]
这个比较明显，Amigo plugin和instant-run有冲突，如果你想启用Amigo的话，请手动关闭instant-run
