### ISSUE TITLE
compat with Jack&Jill

### ISSUE THREAD

**Issue by JackCho** [eleme/Amigo#197]

**Comment by FtheGFW** [comment]
我差不多做完了

**Comment by FtheGFW** [comment]
jack&jill  处理 multi dex 时貌似有问题，没有把本来该放在 maindex 里的类放进去，我之后再继续看看

[google code issue](https://code.google.com/p/android/issues/detail?id=226867&sort=-type%20-status%20-stars&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened)

**Comment by FtheGFW** [comment]
jack & jill 工具链已被 google 废弃，所以关闭这个 issue
