### ISSUE TITLE
关于补丁升级界面（补丁包合并界面）

### ISSUE THREAD

**Issue by wm1993** [eleme/Amigo#198]
@JackCho    手机qq升级会有一个界面，有一个进度条，显示百分子百就合并成功了， Amigo 只是在AndroidManifest中声明指定布局文件，现在会更新的时候会显示白屏（界面是空白的）。
 我的意思是，在这个界面能否获取正在更新的相关信息，比如完成多少（Progress）,这样就可以显示当前进度，给用户友好提示。不知到是否支持这个功能

**Comment by wm1993** [comment]
@JackCho   我的意思是能否在这个界面获取正在更新的相关信息，比如完成多少（Progress）,这样就可以显示当前进度，给用户友好提示。不知打是否支持这个功能

**Comment by wm1993** [comment]
@JackCho    希望能够加入这个功能

**Comment by JackCho** [comment]
Amigo自身的定位是为开发者提供无感知热更新APP的功能，本来就是要淡化用户对热更新的感知。所以我们建议大家在使用 Amigo.work() api的时候，把 theme/layout指定和splash页面相同。暂时我们没有支持这个feature的计划
