### ISSUE TITLE
先调用clear 再调用work会crash

### ISSUE THREAD

**Issue by xujinyang** [eleme/Amigo#2]
![image](https://cloud.githubusercontent.com/assets/4199903/18002133/a8b4d034-6bb8-11e6-972e-77d30befd286.png)

**Comment by JackCho** [comment]
please submit a issue with **english**, maybe other developers beyond China will have the same issue with using Amigo.

you shall not call `Amigo.clear(context) `every time before loading, Amigo will clear previous apk info automatically in [PR](https://github.com/eleme/Amigo/pull/3).

`Amigo.work(context)` isn't need to be called every time either. this method is designed for some time-tense operation like releasing some files in this apk file, it will be executed one single time when a new apk received automatically.

if you still have some questions, please comment below

**Comment by xujinyang** [comment]
ok ,l understand but You can't make sure other people don't use so

**Comment by JackCho** [comment]
I will submit a feature PR which lets Amigo clear working directory automatically when hotfix apk changes, so users will not need to call `Amigo.clear(context)` manually. And also I'd say I will still keep this method in case of user just wants to remove all amigo working dir.
