### ISSUE TITLE
每次尝试都完美的失败了,我心好累

### ISSUE THREAD

**Issue by sunkiha** [eleme/Amigo#200]
不管是自己写 还是用云平台都完美的闪退
还有
  boolean patchWorked = Amigo.hasWorked();
        if (!patchWorked) {
            Amigo.work(this, patchApkFile);
            return;
        }
        Amigo.work(this, patchApkFile);
这段代码我看了很久 请大神指教这个判断有什么用....

**Comment by FtheGFW** [comment]
麻烦上传 logcat日志一下，谢谢
 [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

**Comment by sunkiha** [comment]
![image](https://cloud.githubusercontent.com/assets/8541045/21517829/34c06104-cd1d-11e6-9150-783e74c7203f.png)

**Comment by sunkiha** [comment]
![image](https://cloud.githubusercontent.com/assets/8541045/21517987/34c2e162-cd1e-11e6-8dd7-385a93d9394c.png)

**Comment by peacepassion** [comment]
@sunkiha amigo-sdk请求的patch_info，是自己mock的么？response能贴出来么？

**Comment by sunkiha** [comment]
![image](https://cloud.githubusercontent.com/assets/8541045/21518484/c7520de8-cd21-11e6-94b1-851a8c337aba.png)
完全用的amigo平台 可能是网络环境差时好时坏有时候报最上面的 有时候报最下面的....还有不用AmigoSdk 用Amigo.work()之后为什么再次打开没有任何效果还是原来的....

**Comment by sunkiha** [comment]
target object must not be null 重点在这个 进行了热修复之后再次打开闪退.....

**Comment by JackCho** [comment]
@sunkiha 从`target object must not be null`看应该是Amigo的问题，可能是机型适配问题。麻烦把你机器ROM、厂商、版本等信息发一下，同时麻烦你尝试侠其他机器，看也会出现同样的问题不

**Comment by sunkiha** [comment]
![image](https://cloud.githubusercontent.com/assets/8541045/21536256/5acb03e2-cdbb-11e6-9110-c4987a07af2e.png)

**Comment by JackCho** [comment]
@sunkiha 我尝试一番重现没能重现出来，你方便的时候，可以在其他机器上测一测，确认一下是不是这个设备+ROM的问题。thx

**Comment by JackCho** [comment]
Amigo-Sdk isn't supported any more
