### ISSUE TITLE
Could you guide me to how to use bspatch as it very confusing.

### ISSUE THREAD

**Issue by atulgoswami21** [eleme/Amigo#205]

**Comment by JackCho** [comment]
Amigo receices a valid apk as input through `work`/`workLater`, so you need dispatch a whole new apk to all end-users.  Dispatched apk may be some kind of large, `bsdiff`help to reduce the size with you just need to dispatch the diff patch between your good apk & bug apk.

**Comment by FtheGFW** [comment]
@atulgoswami21 建议你阅读一下 https://amigo.ele.me/#/wiki/platform-intro， 然后尝试一下
