### ISSUE TITLE
about热修复：不想全量下载apk，只想下载差异activity，可以实现不，demo里面没找到

### ISSUE THREAD

**Issue by BatnettWang** [eleme/Amigo#208]
PatchedStandardActivity 没找到 。大牛求指导

**Comment by BatnettWang** [comment]
比如 我只修改了某一个Acitvity中的变量，下载整个app（40M左右）会比较慢，Amigo有没有提供只修改某一个类的热修复方法 ？求大牛指导 。

**Comment by BatnettWang** [comment]
我看到了 bspatch，于是我的思路是 app集成bspatch，从服务端下载补丁apk，利用bspatch 将本地apk和补丁apk合并成newAPK，再用Amigo.work(this, newAPKFile)，实现热更新 。

**Comment by BatnettWang** [comment]
但是有个问题： 必须保证用户第一次下载的目录在指定位置，不然没办法将本地apk和服务端的补丁apk合并 。。。 尴尬了

**Comment by FtheGFW** [comment]
或者使用https://amigo.ele.me/#/wiki/add-sdk, 可以满足你的需求 @BatnettWang

**Comment by BatnettWang** [comment]
兄弟，使用sdk 不还是下载全新的APK嘛？不能为用户达到减少流量的目的。。

**Comment by FtheGFW** [comment]
已经做了差分支持，只是没有更新文档

**Comment by BatnettWang** [comment]
![device-2017-02-08-143904](https://cloud.githubusercontent.com/assets/11208440/22726099/756090d4-ee0c-11e6-958c-e452706d32c2.png)
请问 demo中这个类TestPatchedActivities的startStandard监听是干什么的？缺少me.ele.demo.activity.PatchedStandardActivity  如上图
