### ISSUE TITLE
IntentService not getting called.

### ISSUE THREAD

**Issue by atulgoswami21** [eleme/Amigo#209]
I am calling this function in onCreate of activity but RegistrationIntentService is not getting called.
it is present in both host and patch and also present in manifest.

<service android:name="com.bizzypulse.bizzypulse.RegistrationIntentService" android:exported="false"/>

private void Initialization() {
        Log.d("BaseActivity","Checking Play service");
        if (CommonUtilities.checkPlayServicesNew(mContext)) {
            Log.d("BaseActivity","Sending Registration intent");
            Intent intent = new Intent(mContext, RegistrationIntentService.class);
            startService(intent);
        }
        CommonUtilities.InitAllAlarm(mContext, false);
    }

please take a look at this and thanks in advance.

**Comment by JackCho** [comment]
your reported issue cannot be reproduced, please check again.
if you can reproduce with Amigo demo, that would be the best

**Comment by JackCho** [comment]
no more info, close this temporarily
