### ISSUE TITLE
集成Amigo不生效问题

### ISSUE THREAD

**Issue by yangcaixai** [eleme/Amigo#216]
1.采用立即生效方式后，我的App确实自动重启，但是并没有替换生效成功。然后再使用立即生效方式进行修复我的App挂掉了，logcat里面并没有异常信息。 
2.使用重启生效方式也未生效。
烦请大神帮忙看一下 下面是我的demo源码  感谢大神
--------------------------------------------------------------------------------------------------------------
这是主界面代码：
package com.ycx.amigo;

import android.app.Activity;
import android.os.Bundle;
import android.os.Environment;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import java.io.File;

import me.ele.amigo.Amigo;

public class MainActivity extends Activity implements View.OnClickListener {
    private static final String TAG = MainActivity.class.getSimpleName();
    public static final String APK_NAME = "amigo_test_patch.apk";
    
    private TextView mTextView;
    private Button mButton1;
    private Button mButton2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mTextView = (TextView) findViewById(R.id.tv_text);
        String text = "version code:" + BuildConfig.VERSION_CODE;
        text += "\n";
        text += "version code from host-->" + Amigo.getHostPackageInfo(this, 0).versionCode;
        mTextView.setText(text);
        
        mButton1 = (Button) findViewById(R.id.btn_button1);
        mButton2 = (Button) findViewById(R.id.btn_button2);
        mButton1.setOnClickListener(this);
        mButton2.setOnClickListener(this);
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.btn_button1:
                applyPatchApkImmediately();
                break;
            
            case R.id.btn_button2:
                applyPatchApkLater();
                break;
        }
    }

    public void applyPatchApkImmediately() {
//        File dir = Environment.getExternalStorageDirectory();
        File dir = new File("/data/data/com.ycx.amigo/");
        File patchApkFile = new File(dir, APK_NAME);
        Log.i(TAG, "applyPatchApkImmediately: "+patchApkFile.getAbsolutePath());
        if (!patchApkFile.exists()) {
            Toast.makeText(this,
                    "No amigo_patch.apk found in the directory: " + dir.getAbsolutePath(),
                    Toast.LENGTH_SHORT).show();
            return;
        }
        boolean patchWorked = Amigo.hasWorked();
        Log.i(TAG, "applyPatchApkImmediately: patchWorked "+patchWorked);
        if (!patchWorked) {
            Amigo.work(this, patchApkFile);
            return;
        }
        Amigo.work(this, patchApkFile);
    }

    public void applyPatchApkLater() {
        int i=1/0;
        File dir = Environment.getExternalStorageDirectory();
        File patchApkFile = new File(dir, APK_NAME);
        Log.i(TAG, "applyPatchApkLater: "+patchApkFile.getAbsolutePath());
        if (!patchApkFile.exists()) {
            Toast.makeText(this,
                    "No amigo_patch.apk found in the directory: " + dir.getAbsolutePath(),
                    Toast.LENGTH_SHORT).show();
            return;
        }
        boolean patchWorked = Amigo.hasWorked();
        if (!patchWorked) {
            Amigo.workLater(this, patchApkFile, new Amigo.WorkLaterCallback() {
                @Override
                public void onPatchApkReleased() {
                    Toast.makeText(getApplicationContext(), "dex opt done!", Toast.LENGTH_SHORT).show();
                }
            });
            Toast.makeText(this,
                    "waiting for seconds, and kill this app and relaunch the app to check result",
                    Toast.LENGTH_SHORT).show();
            return;
        }
        Amigo.workLater(this, patchApkFile, new Amigo.WorkLaterCallback() {
            @Override
            public void onPatchApkReleased() {
                Toast.makeText(getApplicationContext(), "dex opt done!", Toast.LENGTH_SHORT).show();
            }
        });
        Toast.makeText(this,
                "waiting for seconds, and kill this app and relaunch the app to check result",
                Toast.LENGTH_SHORT).show();
    }
}
-------------------------------------------------------------------------------------------------------------------
这是Project gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'me.ele:amigo:0.6.4'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

-------------------------------------------------------------------------------------------------------------------
这是Module 的 gradle
apply plugin: 'com.android.application'
apply plugin: 'me.ele.amigo'
android {
    compileSdkVersion 23
    buildToolsVersion '19.1.0'
    defaultConfig {
        applicationId "com.ycx.amigo"
        minSdkVersion 9
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:23.4.0'
    testCompile 'junit:junit:4.12'
}

//开发过程中你可以不想开启Amigo
//你可以把这个定义在mybuild.gradle，以区分debug & release打包
amigo {
    disable true //默认 false
    autoDisableInInstantRunMode true // 默认 true
}

-------------------------------------------------------------------------------------------------------------------
这是Manifest配置文件
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ycx.amigo">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
-------------------------------------------------------------------------------------------------------------------

**Comment by FtheGFW** [comment]
==quote==========================
```groovy
//开发过程中你可以不想开启Amigo
//你可以把这个定义在mybuild.gradle，以区分debug & release打包
amigo {
disable true //默认 false
autoDisableInInstantRunMode true // 默认 true
}
```
==end quote==========================

麻烦改成下面的再试试：
```groovy
amigo {
    disable false
    autoDisableInInstantRunMode true
}
```
