### ISSUE TITLE
Amigo是否能支持加固？

### ISSUE THREAD

**Issue by bhp1127** [eleme/Amigo#218]
您好！
我测试加固包的时候，app不能启动，打印的部分日志如下：
D/me.ele.amigo.AmigoClassLoader: loadClass: can't find amigo-lib in the patch apk, trying to load [me.ele.amigo.Amigo] from original classloader
D/me.ele.amigo.AmigoClassLoader: loadClass: can't find amigo-lib in the patch apk, trying to load [me.ele.amigo.acd] from original classloader

**Comment by JackCho** [comment]
which platform do you use?

**Comment by bhp1127** [comment]
梆梆

**Comment by dyglcc** [comment]
同样的问题+1@JackCho

**Comment by JackCho** [comment]
我的理解是这样的，如果app能正常使用，但是加固之后，app无法正常启动了，这块就是加固厂商的锅了。Amigo没有计划对这类问题做支持
