### ISSUE TITLE
MultiDex问题

### ISSUE THREAD

**Issue by JohnneyLei** [eleme/Amigo#219]
![image](https://cloud.githubusercontent.com/assets/24561261/23496376/c3b464ba-ff58-11e6-8c9f-adebaf3f83f8.png)
集成后发现这个问题，原因可能是因为在Application中调用MultiDex.install(this)前，provider就调用了onCreate。
是否是因为先调用的Amigo.java，此时provider就开始初始化，然后才反射调用Application中attachBaseContext来做MultiDex.install导致；此问题发生在5.0以下机型。可否做一下5.0以下适配，谢谢

**Comment by FtheGFW** [comment]
Thanks, 这个已经做完了，还在测试，(有个 workaround ：如果你现在用的 buildTool 是25.x 的话，可以暂时先降到23.x, 确保所有的ContentProvider等组件被打包在 classes.dex 里)

**Comment by JohnneyLei** [comment]
谢谢，期待测试完成发出来。我这里报错其实是这个provider需要用的一个类没有找到，如果降到23.x来打包，会将provider用到的类也打进去吗？这块不是很懂，谢谢

**Comment by FtheGFW** [comment]
是的

**Comment by FtheGFW** [comment]
已修复，麻烦升级至0.6.6版本,  可以参考 #225
