### ISSUE TITLE
Android Studio 2.3 上的错误提示

### ISSUE THREAD

**Issue by twiceyuan** [eleme/Amigo#220]
Gradle 3.3 & Android Gradle Plugin 2.3.0 下，同步 Gradle 操作后会提示：

```
Error:(3, 0) Cannot set the value of read-only property 'version' for DefaultExternalModuleDependency{group='me.ele', name='amigo', version='0.6.3', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
<a href="openFile:<projectPath>/app/build.gradle">Open File</a>
```

**Comment by JackCho** [comment]
please downgrade your gradle version below 3.0 for now, [here](https://github.com/eleme/Amigo/blob/master/gradle/wrapper/gradle-wrapper.properties) is my config. We will support newest gradle version ASAP
