### ISSUE TITLE
Error:(2, 0) Plugin with id 'me.ele.amigo' not found. 

### ISSUE THREAD

**Issue by pengzhuo** [eleme/Amigo#221]
Android Studio 2.3
Build #AI-162.3764568, built on February 24, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

请问这个要如何解决？

**Comment by FtheGFW** [comment]
buildScript 的 classpath 加了吗
