### ISSUE TITLE
when use gradle3.3 this error happend

### ISSUE THREAD

**Issue by showedboy** [eleme/Amigo#223]
Error:(2, 0) Cannot set the value of read-only property 'version' for DefaultExternalModuleDependency{group='me.ele', name='amigo', version='0.6.4', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
<a href="openFile:C:\Android\studio_work\***\app\build.gradle">Open File</a>
当在根build.gradle添加了classpath 'me.ele:amigo:0.6.4'后出现了这个问题，如果不在项目根添加classpath，会出现Error:(2, 0) Plugin with id 'me.ele.amigo' not found.
<a href="openFile:C:\Android\studio_work\TVAppStore_V3.3_OTT_gradle\app\build.gradle">Open File</a>
希望尽快提供在gradle 3.3环境下的适配方法

**Comment by pandavickey** [comment]
同样遇到gradle3.3环境下编译的问题

**Comment by FtheGFW** [comment]
@pandavickey 请参考 #225
