### ISSUE TITLE
AndroidStudio2.3版本集成问题

### ISSUE THREAD

**Issue by zhousuqiang** [eleme/Amigo#225]
更新到2.3版本后，编译报错：
Error:(3, 0) Cannot set the value of read-only property 'version' for DefaultExternalModuleDependency{group='me.ele', name='amigo', version='0.6.5', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.

请问如何解决呢？

**Comment by FtheGFW** [comment]
麻烦升级一下 amigo 至 0.6.6，由于 0.6.6 中把 amigo plugin 和 amigo-lib 给拆开了，所以需要额外在你的 app 模块的 build.grade 里加上对 amigo-lib 的依赖，例如：
```groovy
apply plugin: 'com.android.application'
apply plugin: 'me.ele.amigo'
...
dependencies {
...
 compile 'me.ele:amigo-lib:0.6.6' // **这个也要加**
}
```
