### ISSUE TITLE
使用Amigo后，导致Application的部分功能缺失 ？

### ISSUE THREAD

**Issue by qinci** [eleme/Amigo#238]
不知道是不是我集成的问题，集成Amigo后registerActivityLifecycleCallbacks没有回调

**Comment by JackCho** [comment]
@FtheGFW 这个问题是不是你昨天修复了的，是Application没有替换回来造成的？

**Comment by qinci** [comment]
@JackCho 我用0.6.6版本，我改一下试试

**Comment by qinci** [comment]
切回compile 'me.ele:amigo-lib:0.6.5'就可以了

**Comment by JackCho** [comment]
上个版本引入的bug，你先使用0.6.5吧。我们会尽早发布新版的

**Comment by qinci** [comment]
好的，谢谢啦
