### ISSUE TITLE
gradle 3.3 编译报错

### ISSUE THREAD

**Issue by zhousuqiang** [eleme/Amigo#243]
Cannot invoke method entries() on null object

**Comment by AndroidSXK** [comment]
我也是3.3，并没有报错

**Comment by wznshuai** [comment]
#240 一样的问题

**Comment by JackCho** [comment]
`
 classpath 'me.ele:amigo:0.6.8'
`
试试这个，修复了

**Comment by zhousuqiang** [comment]
@JackCho 找不到0.6.8版本
Error:Could not find me.ele:amigo-lib:0.6.8.
Required by:
    project :app
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by JackCho** [comment]
@zhousuqiang 是升级 plugin，不升级lib

**Comment by zhousuqiang** [comment]
@JackCho 嗯，按您说的，好了
