### ISSUE TITLE
RuntimeException: Unable to instantiate application

### ISSUE THREAD

**Issue by zhousuqiang** [eleme/Amigo#246]
RuntimeException: Unable to instantiate application me.ele.amigo.Amigo: java.lang.RuntimeException: java.lang.RuntimeException: Initiate amigo files failed (do not have access to /data/data/com.huan.edu.lexue.frontend/code_cache/amigo_odex)
请问这是什么原因导致的呢？

**Comment by zhousuqiang** [comment]
// Caused by: java.lang.RuntimeException: Initiate amigo files failed (do not have access to /data/data/com.huan.edu.lexue.frontend/code_cache/amigo_odex).

// 	at me.ele.amigo.AmigoDirs.ensureAmigoDir(AmigoDirs.java:104)

// 	at me.ele.amigo.AmigoDirs.<init>(AmigoDirs.java:47)

// 	at me.ele.amigo.AmigoDirs.getInstance(AmigoDirs.java:52)

// 	at me.ele.amigo.PatchInfoProvider.getPatchInfoFile(PatchInfoProvider.java:255)

// 	at me.ele.amigo.PatchInfoProvider.readLocked(PatchInfoProvider.java:223)

// 	at me.ele.amigo.PatchInfoProvider.queryWorkingChecksum(PatchInfoProvider.java:120)

// 	at me.ele.amigo.PatchInfoProvider.query(PatchInfoProvider.java:63)

// 	at me.ele.amigo.PatchInfoUtil.getWorkingChecksum(PatchInfoUtil.java:34)

// 	at me.ele.amigo.Amigo.attachApplication(Amigo.java:75)

**Comment by JackCho** [comment]
@zhousuqiang 这个貌似是app私有目录的code_cache文件权限不足，麻烦贴下你的手机厂商、ROM版本。 @FtheGFW 你也跟进一下

**Comment by zhousuqiang** [comment]
@JackCho 我们是用在TV端的，厂商是CH，ROM版本5.1。
请问这个是在启动时anigo进行初始化时报出来的吗?昨晚跑monkey跑出来的，现在手动测试不会出现了。

**Comment by JackCho** [comment]
<img width="795" alt="2017-07-12 10 41 56" src="https://user-images.githubusercontent.com/3806682/28099439-2b2a0b88-66ef-11e7-9b58-160c08972b06.png">
 这里貌似是个 [Android issue](https://code.google.com/p/android/issues/detail?id=225735)

建议系统手动安装再跑一遍Monkey，看看问题还在不

**Comment by zhousuqiang** [comment]
@JackCho 请问在build.gradle里面把disable关闭掉后，还会走上面那些代码吗？这个厂家太较真，所以想暂时先把amigo关闭。

**Comment by JackCho** [comment]
disable意思是禁掉Amigo的所有功能，不会走到上面的代码的

**Comment by zhousuqiang** [comment]
好的，谢谢
