### ISSUE TITLE
依赖都添加了，可是就是找不到类

### ISSUE THREAD

**Issue by franos** [eleme/Amigo#251]
![screenshot from 2017-07-18 15-59-40](https://user-images.githubusercontent.com/10569339/28306675-db5117d4-6b65-11e7-814a-4a4fb08f32a5.png)

![screenshot from 2017-07-18 16-00-41](https://user-images.githubusercontent.com/10569339/28306874-a5c44838-6b66-11e7-90a2-27dacd0031e0.png)
![screenshot from 2017-07-18 16-00-55](https://user-images.githubusercontent.com/10569339/28306877-a9956046-6b66-11e7-8602-f38cf2c4744c.png)

求助!!!

**Comment by JackCho** [comment]
检查下依赖
```groovy
apply plugin: 'me.ele.amigo'

android {
...
}

dependencies {
    ...
    compile 'me.ele:amigo-lib:0.6.7'
}
```

**Comment by franos** [comment]
多谢回答！改用这一句就OK了，为什么不能直接依赖工程呢

**Comment by panhs** [comment]
@franos 我和你一样， 但是找不到A.java类  注释掉可以正常跑了
