### ISSUE TITLE
有关aar热修复

### ISSUE THREAD

**Issue by panhs** [eleme/Amigo#252]
我们这个框架 支持aar和jar库的热更新吗 ，就是对部分代码或代码加资源做热更新修复

**Comment by JackCho** [comment]
可以，这个是全局支持的，不局限局部的更新

**Comment by panhs** [comment]
我们是第三方库的，想偷偷的热更新我们库的，目前直接把apk换成aar文件是不支持的。

**Comment by JackCho** [comment]
@panhs Amigo满足不了你们这种业务场景
