### ISSUE TITLE
eleme/amigo eleme bspatch的联合使用问题？谢谢

### ISSUE THREAD

**Issue by D-Rusty** [eleme/Amigo#258]
现在我手上有一个 old.apk(已安装在手机上的apk),一个new.apk(修复了bug的新apk)，请问我是先使用ZipPatchAsync方法生成diff2.apk(已安装apk，和修复bug的差异版本apk),在使用 BsPatch.workAsync(oldApk, newApk, patch, new BsPatch.BsPatchListener()）方法,将 diff2.apk(已安装apk，和修复bug的差异版本apk)和old.apk进行合并生成bspatc-new.apk,在执行 Amigo.work进行热修复替换吗，谢谢。

**Comment by JackCho** [comment]
1. `new.apk` - 'old.apk' ==> `diff.apk`

2. download `diff.apk` with `old.apk`

3. `old.apk` + 'diff.apk' ==> `new.apk`

4. Amigo.work($new.apk)
