### ISSUE TITLE
请问支持Unity吗？如果不支持，麻烦提供下修改思路呢！！

### ISSUE THREAD

**Issue by tanjiplay** [eleme/Amigo#262]
Unity 更新不了assets目录下的资源, 应该是Unity调用了C底层的接口读取，请问这个怎么处理？

**Comment by JackCho** [comment]
对Unity不了解，如果真的是在底层解析apk的assets，那还真搞不了修复。
提供两个思路，你看行不行
* 自己封装一个方法去读取assets的工具方法，全局都走这个
* hook Unity调用C的方法，自己改

**Comment by tanjiplay** [comment]
好的，我试试！！
