### ISSUE TITLE
amigo只能一次热修复么？

### ISSUE THREAD

**Issue by cheshenghui** [eleme/Amigo#29]
我在测试demo的时候，第一次修改完，热修复是可以的，第二次修改完，就没有效果了，不知道原因，求解

**Comment by peacepassion** [comment]
@cheshenghui 麻烦尽量详细的描述下整个使用步骤

**Comment by cheshenghui** [comment]
1. ./gradlew clean assembleRelease & adb install .../build/outputs/apk/app-release.apk
2. change code wherever you like & ./gradlew clean assembleRelease
3. adb push .../build/outputs/apk/app-release.apk /sdcard/demo.apk
4. kill Amigo demo by yourself & restart to check if your change works

**Comment by peacepassion** [comment]
我又严格按照你的步骤执行了一遍，没发现问题。  
我用的是模拟器。4.4.4  

把你那边的crash栈、测试环境发一下吧

**Comment by cheshenghui** [comment]
没有crash，第一次可以，第二次修改就没有反应了，热更新不了了，我用的是5.0的真机
demo中application中 if (fixedApkFile.exists() && !amigoApkFile.exists())中的!amigoApkFile.exists()是判断data/data/{pn}/files目录下是否存在之前热更新的apk吧？是不是第二次没有通过这里的判断啊？

**Comment by peacepassion** [comment]
@cheshenghui  你是指再次启动的时候没有Patch APK Load过程了？

**Comment by cheshenghui** [comment]
恩 第一次热修复了，第二次又在原基础上修改了demo，然后再kill当前进程，然后再打开app，然后没有出现Patch APK Load过程了

**Comment by peacepassion** [comment]
@cheshenghui 这是正常的。因为app的私有目录下已经加载了一个patch apk，这个时候，是不会再去加载新的patch apk的。   

```java
            File fixedApkFile = new File(Environment.getExternalStorageDirectory(), "demo.apk");
            File amigoApkFile = Amigo.getHotfixApk(this);
            if (fixedApkFile.exists() && !amigoApkFile.exists()) {
                Amigo.work(this, fixedApkFile);
//                Amigo.workLater(this, fixedApkFile);
            }
```

**Comment by cheshenghui** [comment]
强制将sdcard下的patch apk覆盖拷贝到私有目录下？具体怎么做，不太懂，能解释一下么，，或者说 在哪覆盖拷贝 需要注意什么？

**Comment by peacepassion** [comment]
@cheshenghui 把`ApplicationContext#onCreate()`的实现换为： 

```java
    @Override
    public void onCreate() {
        super.onCreate();
        Log.e(TAG, "onCreate: " + this);

        if (ProcessUtils.isMainProcess(this)) {
            File fixedApkFile = new File(Environment.getExternalStorageDirectory(), "demo.apk");
            if (fixedApkFile.exists()) {
                FileUtils.copyFile(fixedApkFile, Amigo.getHotfixApk(this));
            }
        }
    }
```  

这样的话，应该就会每次启动的时候都会取sdcard目录下的demo.apk了。

**Comment by cheshenghui** [comment]
你的意思是 只要将patch apk拷贝到app的files目录下，不需要调用work这个函数就自动hotfix了？

**Comment by JackCho** [comment]
@cheshenghui 调用work是指立马生效，如果copy过后不调用work的话，下次启动生效

**Comment by cheshenghui** [comment]
if (ProcessUtils.isMainProcess(this)) {
            File fixedApkFile = new File(Environment.getExternalStorageDirectory(), "demo.apk");
            if (fixedApkFile.exists()) {
                FileUtils.copyFile(fixedApkFile, Amigo.getHotfixApk(this));
            }
        }
这样 出错了

**Comment by captain-miao** [comment]
这里有三个版本的控制

- Apk的版本，假设：apkVer
- 已经修复的版本，假设：fixedVer
- 最新修复的版本，假设：lastVer

```
if(lastVer > apkVer){
	if(lastVer > fixedVer){
		...
		Amigo.work(this, fixedApkFile);
	}
}
```

@JackCho 所以需要改一些逻辑哈
