### ISSUE TITLE
java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)

### ISSUE THREAD

**Issue by dxiaogang** [eleme/Amigo#36]
![image](https://cloud.githubusercontent.com/assets/10472084/18243061/de0a1ac0-738b-11e6-9a90-f758f7353d5a.png)

项目集成了espresso,mockito做测试

**Comment by dxiaogang** [comment]
权限已经加了的.

**Comment by JackCho** [comment]
看日志，和Amigo没啥关联

**Comment by dxiaogang** [comment]
我也好奇,但是我关掉Amigo就没问题了.😂  @JackCho

**Comment by JackCho** [comment]
what happens when you run app directly?

**Comment by JackCho** [comment]
@peacepassion help to see what's wrong here

**Comment by dxiaogang** [comment]
这两天有事,没来得及回,抱歉:
补充下:
实测真实手机 酷派大神X7,Android4.4
日志:
![image](https://cloud.githubusercontent.com/assets/10472084/18301863/1571b2f8-7507-11e6-9015-d52a62eeb573.png)
操作步骤:
其实都是按那个来的.
项目配置:
![image](https://cloud.githubusercontent.com/assets/10472084/18301892/3682f2d6-7507-11e6-88eb-213ac331347c.png)
![image](https://cloud.githubusercontent.com/assets/10472084/18301902/45d99f64-7507-11e6-9805-765c1baabc0a.png)
代码设置:
![image](https://cloud.githubusercontent.com/assets/10472084/18301916/6420b8ea-7507-11e6-816c-140a67b464c7.png)

还有什么需要帮助的可以直接@我.

**Comment by dxiaogang** [comment]
还有日志建议加个开关,如果加载失败,希望不加载插件使用原来的,不然打开就崩了

**Comment by peacepassion** [comment]
@dxiaogang 看日志感觉像是Amigo改了某个文件夹或者文件的权限，刚好这个文件也需要jacoco访问，然后就贵了。   我没用过jacoco，可能会需要花段时间研究一下。

**Comment by JackCho** [comment]
@dxiaogang 加载hotfix apk失败的话，直接加载原来的apk，这个建议的PR已merge

**Comment by JackCho** [comment]
@dxiaogang 这个问题还存在的么？没有的话，就close这个issue了
