### ISSUE TITLE
释放Apk慢，能否优化

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#42]
目前释放Apk慢。
https://github.com/asLody/TurboDex 这个项目据说能加速load dex ,不知是否有帮助。

**Comment by JackCho** [comment]
@c1024 TurboDex has nothing to do here, if I'm right, it just helps app to skip dex2oat & may only work on art. 

`Amigo.workLater(context, apkFile)` may be your option

**Comment by c1024** [comment]
Amigo.workLater(context, apkFile)我测试会 crash ;

打印出如下日志
09-08 10:24:17.416 19794-19794/com.mocoo.dfwc E/Amigo: demoApkChecksum-->3625666893, sig--->3625666893
09-08 10:24:17.419 19794-19794/com.mocoo.dfwc E/Amigo: opt dexFile-->/data/user/0/com.mocoo.dfwc/files/amigo/dex_opt/classes.dex
09-08 10:24:17.419 19794-19794/com.mocoo.dfwc E/Amigo: savedChecksum-->, checksum--->1733022618

checkDexAndSoChecksum这个方法里面崩溃了

**Comment by peacepassion** [comment]
@c1024 worklater需要进程重启一次patch才能生效的。所以，崩溃后，你再打开app看一下是否已经加载了patch apk.

**Comment by peacepassion** [comment]
@c1024 还有一点，别忘了把patch apk修改为不会crash的apk

**Comment by c1024** [comment]
@peacepassion worklater进程有重启，但是会崩溃。

**Comment by peacepassion** [comment]
@c1024 好的，你用的就是demo么？

**Comment by c1024** [comment]
@peacepassion 不是。不过之前有测试demo, 把work改成worklater也是有问题

**Comment by peacepassion** [comment]
@c1024 不会吧，这个项目里的demo是OK的呀，你再试一下这个demo, 把work改为workLater，还有问题的话，把log发上来看一下。

**Comment by c1024** [comment]
@peacepassion demo会崩，如果在释放apk突然崩溃，导致释放apk没有运行完，下次启动会崩溃

**Comment by JackCho** [comment]
@c1024 这个问题应该是修复了，但是目前jcenter还没升级，我让 @peacepassion 帮忙确认一下

**Comment by c1024** [comment]
@JackCho 您是指哪个问题

**Comment by JackCho** [comment]
@c1024 please try with `classpath 'me.ele:amigo:0.0.8'`

**Comment by c1024** [comment]
@JackCho 好的，明天我试一下

**Comment by c1024** [comment]
@JackCho 好的，明天我试一下

**Comment by c1024** [comment]
@JackCho 我试了一下还是有问题。
测试了一下demo ， 

- 如果在释放apk过程中崩溃，下次启动会崩溃，错误日志如下：

09-09 09:41:52.201 6600-6600/me.ele.amigo.demo W/System.err: me.ele.amigo.Amigo$LoadPatchApkException: java.lang.ClassNotFoundException: Didn't find class "me.ele.amigo.acd" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
09-09 09:41:52.202 6600-6600/me.ele.amigo.demo W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Amigo.java:192)
09-09 09:41:52.202 6600-6600/me.ele.amigo.demo W/System.err:     at me.ele.amigo.Amigo.onCreate(Amigo.java:132)
09-09 09:41:52.204 6600-6600/me.ele.amigo.demo W/System.err:     at me.ele.amigo.Amigo.runOriginalApplication(Amigo.java:214)
09-09 09:41:52.204 6600-6600/me.ele.amigo.demo W/System.err:     at me.ele.amigo.Amigo.runPatchApk(Amigo.java:190)
09-09 09:41:55.822 5049-7178/? W/ActivityManager: Scheduling restart of crashed service me.ele.amigo.demo/me.ele.amigo.AmigoService in 1000ms

**Comment by c1024** [comment]
保存的savedChecksum为空,还是没解决。
有时补丁会突然失效

**Comment by FtheGFW** [comment]
我测试了一下，没法复现你说的问题，方便的话你如何测试demo的详细步骤或代码贴上来

**Comment by c1024** [comment]
@FtheGFW 用最新demo测试，workLater还是有一定概率崩溃。
测试步骤如下：
1./gradlew clean assembleRelease & adb install .../build/outputs/apk/app-release.apk
2change code wherever you like & ./gradlew clean assembleRelease
3adb push .../build/outputs/apk/app-release.apk /sdcard/demo.apk
4click the "apply patch apk" button, and wait a time, press fab button ,may crash

**Comment by FtheGFW** [comment]
从你上面列出的步骤看不出问题原因， 把你测试的手机品牌，rom，api版本等信息顺便贴一下吧 @c1024

**Comment by c1024** [comment]
@FtheGFW 测试手机是Nexus 6p Android6.0系统。之前测试其他手机，发现Android 5.0以上系统都有类似问题

**Comment by FtheGFW** [comment]
intersting, 在我们的设备上暂时没法复现这个问题额

**Comment by ideazoom** [comment]
需要修复补丁的apk怎么生成呢？？ 比如我的APK有10M, 但A类中的方法有致命问题需要修复，我怎么生成补丁APK呢？？

**Comment by FtheGFW** [comment]
请参考readme，然后你的问题也不应该提在这个issue下
