### ISSUE TITLE
Amigo only take effect at first fix,then failed at second. And #29 can't solve it.

### ISSUE THREAD

**Issue by letyouthgoon** [eleme/Amigo#48]
![image](https://cloud.githubusercontent.com/assets/3445575/18378699/0b6a2e2a-76a1-11e6-910d-9705843fa0f0.png)

**Comment by FtheGFW** [comment]
需要你提供一下具体做了哪些操作, 步骤

**Comment by letyouthgoon** [comment]
@FtheGFW 

./gradlew clean assembleRelease & adb install .../build/outputs/apk/app-release.apk
change code wherever you like & ./gradlew clean assembleRelease
adb push .../build/outputs/apk/app-release.apk /sdcard/demo.apk
kill Amigo demo by yourself & restart to check if your change works
________________________________________________________________________ok
change code wherever you like & ./gradlew clean assembleRelease
adb push .../build/outputs/apk/app-release.apk /sdcard/demo.apk
kill Amigo demo by yourself & restart to check if your change works
________________________________________________________________________no effect

**Comment by dxiaogang** [comment]
same as above .

**Comment by FtheGFW** [comment]
OK, 我觉得这个问题在[#29](https://github.com/eleme/Amigo/issues/29)中 @peacepassion 解释的比较清晰了，第二次load apk的时候，检测到在/data/data/me.ele.amigo.demo/files/amigo/下已存在一个demo.apk，然后就跳过load新的patch apk了

**Comment by letyouthgoon** [comment]
@Override
    public void onCreate() {
        super.onCreate();
        Log.e(TAG, "onCreate: " + this);

        if (ProcessUtils.isMainProcess(this)) {
            File fixedApkFile = new File(Environment.getExternalStorageDirectory(), "demo.apk");
            if (fixedApkFile.exists()) {
                FileUtils.copyFile(fixedApkFile, Amigo.getHotfixApk(this));
            }
        }
    }
so，这个就是＃29中的解决方案，然后报的就是本问题发的截图，现象是不停闪动。

**Comment by FtheGFW** [comment]
obviously, 陷入死循环了，建议你先用MD5比较一下fixedApkFile(新的pathc apk) 和 amigoApkFile (/data/data/me.ele.amigo.demo/files/amigo/demo.apk) 的md5值，然后如果这二者不同，再覆盖amigoApkFile

**Comment by FtheGFW** [comment]
或者简单暴力点，就直接清楚app数据

**Comment by JackCho** [comment]
@letyouthgoon demo已更新，更容易理解Amigo的使用
