### ISSUE TITLE
使用Amigo的时候Gradle遇到了NullPoint错误

### ISSUE THREAD

**Issue by Witype** [eleme/Amigo#53]
Error:Execution failed for task ':app:processDebugManifest'.
> java.lang.NullPointerException (no error message)

Project gradle
`
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-rc2'
        classpath 'me.ele:amigo:0.0.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
`
android studio 2.2 RC2
谢谢！

**Comment by FtheGFW** [comment]
暂时需要在Manifest里指定自定义的Application，以及amigo_layout和amigo_theme两个meta-data，具体参考项目里的demo

**Comment by FtheGFW** [comment]
已修复，https://github.com/eleme/Amigo/pull/54
