### ISSUE TITLE
通过gralde文件能更新版本号么，还是要在AndroidManifest中设置

### ISSUE THREAD

**Issue by letyouthgoon** [eleme/Amigo#66]

**Comment by peacepassion** [comment]
版本管理与正常的android app开发一样。

**Comment by letyouthgoon** [comment]
测试过么，同一次修复，增加gradle中versioncode，并没有生效，其他部分生效。

**Comment by peacepassion** [comment]
![Uploading image.png…]()

看上去没啥问题。

**Comment by peacepassion** [comment]
![image](https://cloud.githubusercontent.com/assets/5254121/18624509/d89309f4-7e7a-11e6-863f-a505560e70ff.png)
![image](https://cloud.githubusercontent.com/assets/5254121/18624512/e1201ed6-7e7a-11e6-933d-7e0b29eaf99a.png) 

我这边看上去没啥问题
