### ISSUE TITLE
手机ota,之前更新的补丁能正常运行吗？

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#68]
ART模式下，厂商ota时，需要对安装的所有应用做全量的AOT编译。用Amigo打补丁后，如果手机ota更新，补丁能正常运行吗？

**Comment by peacepassion** [comment]
我们已经有同事在着手解决这个问题了  @2dxgujun

**Comment by 2dxgujun** [comment]
https://github.com/eleme/Amigo/pull/64
解决方法：patch dex的dex2oat编译输出到code_cache目录下，ota之后code_cache会被清空，amigo会重新做一次dex2oat
