### ISSUE TITLE
In my project , not playing demo appear a error by the way of recommended config.

### ISSUE THREAD

**Issue by fldroid** [eleme/Amigo#71]
"classpath 'me.ele:amigo:0.1.0'" isn't "compile 'me.ele:amigo:0.1.0'" or "compile 'me.ele:amigo-lib:0.1.0'" ?
What's the usage of "Amigo/buildSrc"?
What should i configure ?

**Error:(2, 0) Plugin with id 'me.ele.amigo' not found.**

**Comment by peacepassion** [comment]
![image](https://cloud.githubusercontent.com/assets/5254121/18662126/7d435ed8-7f4b-11e6-980d-b98529a63376.png) 

Just need to configure plugin dependency.  

BuildSrc is for development, not usage.

**Comment by fldroid** [comment]
Forgive me for not noticing **“project's build.gradle”**  and **"module's build.gradle"**, thank you for you answer in time.
