### ISSUE TITLE
Can't get instance before initialized

### ISSUE THREAD

**Issue by wznshuai** [eleme/Amigo#79]
use demo
1.first click APPLY PATCH APK button goto fix success
2.when click again get this exception (Can't get instance before initialized)

  can't multi fix ?

**Comment by JackCho** [comment]
This issue is known to our team, we're working on this, please watch this issue for update news
https://github.com/eleme/Amigo/issues/73

**Comment by peacepassion** [comment]
@wznshuai Check the latest demo please.

**Comment by wznshuai** [comment]
@peacepassion where is class A? in HomeActivity,infoView.setText(A.getDes());

**Comment by peacepassion** [comment]
@wznshuai `A.java`  is located in two folders.  

![image](https://cloud.githubusercontent.com/assets/5254121/18780330/9e934ba0-81af-11e6-9b24-ccfc582b7f57.png)

**Comment by wznshuai** [comment]
@peacepassion thanks
