### ISSUE TITLE
应用如果是多进程架构，有可能主进程已经运行补丁，其他进程没有？

### ISSUE THREAD

**Issue by c1024** [eleme/Amigo#82]
在Amigo的onCreate里面有如下代码：
```
if (!ProcessUtils.isMainProcess(this) && isPatchApkFirstRun()) {
                Log.e(TAG, "None main process and patch apk is not released yet");
                runOriginalApplication();
                return;
            }

            // only release loaded apk in the main process
            runPatchApk();
```

按照上述代码，release apk只在主进程。如果是用workLater的话，当应用重新启动时，主进程relase apk, 然后运行补丁程序，而其他程序继续运行原来的程序？是这样吗？

**Comment by peacepassion** [comment]
1. workLater不会在启动时释放，会在host进程运行后台释放，当host再次启动，patch如果已经释放完成，就直接加载patch了。  

2. 这段代码主要用在work流程中，由于释放apk的时候，是有一个前台Activity的，而且一般非主进程出问题的可能性不高，所以这里只允许在主进程打patch

**Comment by c1024** [comment]
@peacepassion 谢谢。之前想错了。
