### ISSUE TITLE
运行出现这个错误是怎么回事？

### ISSUE THREAD

**Issue by zhanggx** [eleme/Amigo#85]
Unable to create application me.ele.amigo.Amigo: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "me.ele.amigo.acd" on path: DexPathList[[zip file "/data/app/******************-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4641)

**Comment by peacepassion** [comment]
用的是0.1.0么？

**Comment by zhanggx** [comment]
我将源代码复制到我的项目中，然后编译运行。 搜索了一下， 在app\build\generated\source\amigo\debug\me\ele\amigo这个目录出现了acd.java文件，但是没有像例子一下出现acd.class， 应该没有编译，不知道哪个步骤出了问题。

**Comment by peacepassion** [comment]
@zhanggx 麻烦试一下先clean，再build一下看看acd.class有没有生成

**Comment by JackCho** [comment]
nothing can be done here without any further information
