### ISSUE TITLE
AndroidManifest.xml未更新？

### ISSUE THREAD

**Issue by zhanggx** [eleme/Amigo#89]
使用了Amigo，可以成功替换新包，但是好像AndroidManifest.xml未更新？获取的版本号和版本名称还是旧的，新加的Activity也没生效。

**Comment by peacepassion** [comment]
AndroidManifest是系统安装时处理掉的，没有机会加载patch包里的。  

版本号如果是通过BuildConfig.java取的话，肯定是新的。  

新加的activity已经提了PR。

**Comment by JackCho** [comment]
https://github.com/eleme/Amigo/pull/86
