### ISSUE TITLE
about bspatch

### ISSUE THREAD

**Issue by wznshuai** [eleme/Amigo#97]
1、current running is Host APK,make  bspatch by host apk
2、current running is patch1.apk, if again fix this apk , make bspatch base which? patch1.apk or host apk?
3、need full update , we make bspatch base which?

  thanks

**Comment by JackCho** [comment]
good question!

 * first condition is clear, no more explanation
 * amigo doesn't do anything about bspatch, so you can make diff based whichever you like. anyway `patch1.apk` is recommanded.
 * full update just needs to download a whole apk, bspatch is useless here
